### PR TITLE
move owid preprocessor to owid/covid19

### PR DESCRIPTION
**Pull request by hanlu09205**
move owid preprocessor to owid/covid19
add code to generate tmcf
add mcf
add README

---
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/data/363)

### CODE REVIEW

**Review by hanlu09205 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/363)* status: 0 of 5 files reviewed, 2 unresolved discussions

___
*[scripts/ourworldindata/covid19/OurWorldInData_Covid19_StatisticalVariables.mcf, line 1 at r1](https://reviewable.io/reviews/datacommonsorg/data/363#-MQu8wcz0KwNn-LuMIMD:-MQu8wcz0KwNn-LuMIME:b-ug94zg) ([raw file](https://github.com/datacommonsorg/data/blob/262b96b4ef71c74ed61e8b61547246b5086864c3/scripts/ourworldindata/covid19/OurWorldInData_Covid19_StatisticalVariables.mcf#L1)):*
> ```
> Node: dcid:CumulativeCount_Vaccine_COVID_19_Administered
> ```

Reading from COVIDTracking_States_StatisticalVariables.mcf, I am not sure whether this file shall contain all the StarVars or just the new ones the import defines. 
I am thinking the first, since this would be needed for import, but want to confirm with u before doing the work. 
___
*[scripts/ourworldindata/covid19/README.md, line 20 at r1](https://reviewable.io/reviews/datacommonsorg/data/363#-MQu9NJQ5SH91X-lKYi2:-MQu9NJQ5SH91X-lKYi3:b-nsb1uv) ([raw file](https://github.com/datacommonsorg/data/blob/262b96b4ef71c74ed61e8b61547246b5086864c3/scripts/ourworldindata/covid19/README.md#L20)):*
> ```Markdown
> 
> ```bash
> python3 preprocess_csv.py
> ```

I didn't add the test code as after reading historic_state_data/preprocess_csv_test.py, I didn't get what it's testing. 
Sure, it compares generated vs expected tmcf, but it never calls preprocess_csv to do the work, instead writing some new code in test.

**Review by pradh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/363)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @hanlu09205)

___
*[scripts/ourworldindata/covid19/OurWorldInData_Covid19.tmcf, line 1 at r2](https://reviewable.io/reviews/datacommonsorg/data/363#-MQwOfbV0x_o9z9TX9eb:-MQwOfbV0x_o9z9TX9ec:b-523wzy) ([raw file](https://github.com/datacommonsorg/data/blob/03ff5cf7e7f5f17635a3ed2e7a51561f51cbc6e9/scripts/ourworldindata/covid19/OurWorldInData_Covid19.tmcf#L1)):*
> ```
> Node: E:OurWorldInData_Covid19->E0
> ```

We can drop this file (since you're generating) and the full CSV (in the interest of a smaller tree) ?

This one will anyway show up in test_data...
___
*[scripts/ourworldindata/covid19/OurWorldInData_Covid19_StatisticalVariables.mcf, line 1 at r1](https://reviewable.io/reviews/datacommonsorg/data/363#-MQu8wcz0KwNn-LuMIMD:-MQwOFXqBiPaNA1Alwbz:bkv4hgg) ([raw file](https://github.com/datacommonsorg/data/blob/262b96b4ef71c74ed61e8b61547246b5086864c3/scripts/ourworldindata/covid19/OurWorldInData_Covid19_StatisticalVariables.mcf#L1)):*
<details><summary><i>Previously, hanlu09205 wrote…</i></summary><blockquote>

Reading from COVIDTracking_States_StatisticalVariables.mcf, I am not sure whether this file shall contain all the StarVars or just the new ones the import defines. 
I am thinking the first, since this would be needed for import, but want to confirm with u before doing the work. 
</blockquote></details>

This file need not be here at all. It is when external folks add a stat-var that we need to then add to google3. You have already added the stat-var there, so we can skip here.
___
*[scripts/ourworldindata/covid19/README.md, line 20 at r1](https://reviewable.io/reviews/datacommonsorg/data/363#-MQu9NJQ5SH91X-lKYi2:-MQwOUMq4ntKcJ_zzh0e:b-hi08yv) ([raw file](https://github.com/datacommonsorg/data/blob/262b96b4ef71c74ed61e8b61547246b5086864c3/scripts/ourworldindata/covid19/README.md#L20)):*
<details><summary><i>Previously, hanlu09205 wrote…</i></summary><blockquote>

I didn't add the test code as after reading historic_state_data/preprocess_csv_test.py, I didn't get what it's testing. 
Sure, it compares generated vs expected tmcf, but it never calls preprocess_csv to do the work, instead writing some new code in test. 

</blockquote></details>

Please refer to some other tests... you can for example fake the "download" part, and test cleaning and TMCF gen.
___
*[scripts/ourworldindata/covid19/README.md, line 8 at r2](https://reviewable.io/reviews/datacommonsorg/data/363#-MQwP1K16obpbVBWMq5G:-MQwP1K16obpbVBWMq5H:b-6o70ea) ([raw file](https://github.com/datacommonsorg/data/blob/03ff5cf7e7f5f17635a3ed2e7a51561f51cbc6e9/scripts/ourworldindata/covid19/README.md#L8)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> - [OurWorldInData_Covid19.csv](OurWorldInData_Covid19.csv): the cleaned CSV.
> - [OurWorldInData_Covid19.tmcf](OurWorldInData_Covid19.tmcf): the mapping file (Template MCF).
> - [OurWorldInData_Covid19_StatisticalVariables.mcf](OurWorldInData_Covid19_StatisticalVariables.mcf):
>   the new StatisticalVariables defined for this dataset.
> ```
</details>


Just list what artifacts are produced by the script... and what is relied on (a list of stat-var-ids)

**Review by hanlu09205 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/363)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @hanlu09205 and @pradh)

___
*[scripts/ourworldindata/covid19/OurWorldInData_Covid19.tmcf, line 1 at r2](https://reviewable.io/reviews/datacommonsorg/data/363#-MQwOfbV0x_o9z9TX9eb:-MQwqNfe3S6_KtlvjSsn:b-czsxvx) ([raw file](https://github.com/datacommonsorg/data/blob/03ff5cf7e7f5f17635a3ed2e7a51561f51cbc6e9/scripts/ourworldindata/covid19/OurWorldInData_Covid19.tmcf#L1)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

We can drop this file (since you're generating) and the full CSV (in the interest of a smaller tree) ?

This one will anyway show up in test_data...
</blockquote></details>

A, I c. 
Then the test will make senses. 
___
*[scripts/ourworldindata/covid19/OurWorldInData_Covid19_StatisticalVariables.mcf, line 1 at r1](https://reviewable.io/reviews/datacommonsorg/data/363#-MQu8wcz0KwNn-LuMIMD:-MQwqKs4DRuQrmF9q2Ht:b9uut6s) ([raw file](https://github.com/datacommonsorg/data/blob/262b96b4ef71c74ed61e8b61547246b5086864c3/scripts/ourworldindata/covid19/OurWorldInData_Covid19_StatisticalVariables.mcf#L1)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

This file need not be here at all. It is when external folks add a stat-var that we need to then add to google3. You have already added the stat-var there, so we can skip here.
</blockquote></details>

Got it. Removed.
___
*[scripts/ourworldindata/covid19/README.md, line 20 at r1](https://reviewable.io/reviews/datacommonsorg/data/363#-MQu9NJQ5SH91X-lKYi2:-MQwrnal22LaKdA-k8Zk:b-szsddz) ([raw file](https://github.com/datacommonsorg/data/blob/262b96b4ef71c74ed61e8b61547246b5086864c3/scripts/ourworldindata/covid19/README.md#L20)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

Please refer to some other tests... you can for example fake the "download" part, and test cleaning and TMCF gen.
</blockquote></details>

Makes sense. 
I was confused by those .csv and .tmcf which already there, and test didn't call pre-processor.
Will add it in the next round.

**Review by hanlu09205 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/363)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @pradh)

___
*[scripts/ourworldindata/covid19/README.md, line 8 at r2](https://reviewable.io/reviews/datacommonsorg/data/363#-MQwP1K16obpbVBWMq5G:-MQwt1rrBESvQFA80yNz:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/03ff5cf7e7f5f17635a3ed2e7a51561f51cbc6e9/scripts/ourworldindata/covid19/README.md#L8)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> - [OurWorldInData_Covid19.csv](OurWorldInData_Covid19.csv): the cleaned CSV.
> - [OurWorldInData_Covid19.tmcf](OurWorldInData_Covid19.tmcf): the mapping file (Template MCF).
> - [OurWorldInData_Covid19_StatisticalVariables.mcf](OurWorldInData_Covid19_StatisticalVariables.mcf):
>   the new StatisticalVariables defined for this dataset.
> ```

Just list what artifacts are produced by the script... and what is relied on (a list of stat-var-ids)
</blockquote></details>

Done.

**Review by pradh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/363)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @hanlu09205 and @pradh)

___
*[scripts/ourworldindata/covid19/README.md, line 8 at r2](https://reviewable.io/reviews/datacommonsorg/data/363#-MQwP1K16obpbVBWMq5G:-MQxTMNa2VAwv-Y4xARi:bjbc48a) ([raw file](https://github.com/datacommonsorg/data/blob/03ff5cf7e7f5f17635a3ed2e7a51561f51cbc6e9/scripts/ourworldindata/covid19/README.md#L8)):*
<details><summary><i>Previously, hanlu09205 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Could you format it better: https://screenshot.googleplex.com/36Mcaj69SejLKvf

**Review by pradh — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/363)* status: all files reviewed, 4 unresolved discussions (waiting on @hanlu09205 and @pradh)

**Review by pradh — APPROVED** [review]

**Pull request merged**
