### PR TITLE
Remove .gitatttributes

### PR DESCRIPTION
**Pull request by ajaits**
Remove .gitattributes file.

Restored small csv test files from git LFS to normal csv:
```
for file in $(git lfs ls-files | grep test | cut -d\* -f2); do
   cp $file tmp/
   git lfs untrack $file
   git rm -cached $file
   git commit -m "remove git LFS files"
   git push -u origin gitlfs
   git add -f $file
   cp tmp/$(basename $file) $file
done
git commit -m "restore original files"
git push -u origin gitlfs
```

### CODE REVIEW

**Review by Abilityguy — COMMENTED** [review]
`tools/place_name_resolver/testdata/input_basic.csv` is still a Git LFS file. Is that alright?

**Comment by ajaits** [comment]
I did the above steps, but it doesn't seem to show the diff. Locally it shows the file content after untrack and update. It is ok for now as the tests are passing.

**Comment by ajaits** [comment]
> `tools/place_name_resolver/testdata/input_basic.csv` is still a Git LFS file. Is that alright?

**Review by Abilityguy — APPROVED** [review]
> I did the above steps, but it doesn't seem to show the diff. Locally it shows the file content after untrack and update. It is ok for now as the tests are passing.

I see. The changes look good. Thanks!.

**Pull request merged**
