### PR TITLE
India RBI Data :  State-wise Unemployment Rate

### PR DESCRIPTION
**Pull request by thejeshgn**
- Added State-wise Unemployment Rate dataset
- For the years
- 1993-94 
- 1999-00 
- 2004-05 
- 2009-10 
- 2011-12 
- 2017-18 
- 2018-19

---
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/data/395)

### CODE REVIEW

**Review by pradh — APPROVED** [review]
Thanks for the PR!  One question on the dataset, and a few nits.

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/395#-:-MT6cjUc9dM9BcJceOK6:bh7h5f3)* status: 0 of 12 files reviewed, 5 unresolved discussions (waiting on @thejeshgn)

___
*[scripts/india_rbi/unemployment_rate_india/preprocess.py, line 81 at r1](https://reviewable.io/reviews/datacommonsorg/data/395#-MT6b0dk4ssHYWQzFrg-:-MT6b0dk4ssHYWQzFrg0:bsybh4t) ([raw file](https://github.com/datacommonsorg/data/blob/7628ba3762b046da2c8203e7433e756c400e5993/scripts/india_rbi/unemployment_rate_india/preprocess.py#L81)):*
> ```
> "Telangana": "IN-TG",
> ```
nit: Looks like a duplicate
___
*[scripts/india_rbi/unemployment_rate_india/preprocess.py, line 113 at r1](https://reviewable.io/reviews/datacommonsorg/data/395#-MT6bz0c-lMqrg8HqT43:-MT6bz0dErUxaaqtbudt:b-1qioyi) ([raw file](https://github.com/datacommonsorg/data/blob/7628ba3762b046da2c8203e7433e756c400e5993/scripts/india_rbi/unemployment_rate_india/preprocess.py#L113)):*
> ```
> FINACIAL
> ```
nit: FINANCIAL
___
*[scripts/india_rbi/unemployment_rate_india/preprocess_test.py, line 51 at r1](https://reviewable.io/reviews/datacommonsorg/data/395#-MT6cZHl7yPf5f3BZmtN:-MT6cZHl7yPf5f3BZmtO:b-446m03) ([raw file](https://github.com/datacommonsorg/data/blob/7628ba3762b046da2c8203e7433e756c400e5993/scripts/india_rbi/unemployment_rate_india/preprocess_test.py#L51)):*
> ```
> self.assertTrue(expected_data == result_data)
> ```
nit:

```
self.assertEqual(expected_data, result_data)
```

So that on failure, the diffs will be seen.
___
*[scripts/india_rbi/unemployment_rate_india/README.md, line 11 at r1](https://reviewable.io/reviews/datacommonsorg/data/395#-MT6bnGL5IdjNnfCK54h:-MT6bnGL5IdjNnfCK54i:b-93wgk9) ([raw file](https://github.com/datacommonsorg/data/blob/7628ba3762b046da2c8203e7433e756c400e5993/scripts/india_rbi/unemployment_rate_india/README.md#L11)):*
> ```
> download as xlsx
> ```

To confirm, there is no overall unemploymentRate for a state (across urban/rural) ?
___
*[scripts/india_rbi/unemployment_rate_india/README.md, line 16 at r1](https://reviewable.io/reviews/datacommonsorg/data/395#-MT6_tDGCh3TrV3_-uUg:-MT6_tDGCh3TrV3_-uUh:br21u9u) ([raw file](https://github.com/datacommonsorg/data/blob/7628ba3762b046da2c8203e7433e756c400e5993/scripts/india_rbi/unemployment_rate_india/README.md#L16)):*
> ```
> Poverty data is per state and by financial year. 
> ```
nit: Unemployment rate

**Review by pradh — COMMENTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/395)* status: all files reviewed, 5 unresolved discussions (waiting on @thejeshgn)

**Review by thejeshgn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/395)* status: 9 of 12 files reviewed, 1 unresolved discussion (waiting on @pradh)

___
*[scripts/india_rbi/unemployment_rate_india/preprocess.py, line 81 at r1](https://reviewable.io/reviews/datacommonsorg/data/395#-MT6b0dk4ssHYWQzFrg-:-MT6rlADCnwaocoCxOrl:bb6un1j) ([raw file](https://github.com/datacommonsorg/data/blob/7628ba3762b046da2c8203e7433e756c400e5993/scripts/india_rbi/unemployment_rate_india/preprocess.py#L81)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> "Telangana": "IN-TG",
> ```
nit: Looks like a duplicate
</blockquote></details>

Done
___
*[scripts/india_rbi/unemployment_rate_india/README.md, line 11 at r1](https://reviewable.io/reviews/datacommonsorg/data/395#-MT6bnGL5IdjNnfCK54h:-MT6szRa3JjsaQrhKta0:b2nhswy) ([raw file](https://github.com/datacommonsorg/data/blob/7628ba3762b046da2c8203e7433e756c400e5993/scripts/india_rbi/unemployment_rate_india/README.md#L11)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> download as xlsx
> ```

To confirm, there is no overall unemploymentRate for a state (across urban/rural) ?
</blockquote></details>

Yes

**Review by pradh — APPROVED** [review]
Thanks for the fixes!

**Pull request merged**
