### PR TITLE
Revert "Internal change" --

### PR DESCRIPTION
**Pull request by tjann**
I had checked the commit log but did not look into the diff--this commit wiped the data repo except for the
schema directory.

This reverts commit ed1d6d3c612a8b81201342bb389689283c7dcbaa.

### CODE REVIEW

**Comment by tjann** [comment]
`git diff 12e468fb3d6a4870c96e70370b199988c2c0a63a 67ad3bf984622112e6bc292a5f444e21c2a2a455` outputs no diffs. 12e468fb3d6a4870c96e70370b199988c2c0a63a is the latest good commit (Jay's Import automation configs #186  )

**Comment by beets** [comment]
There's a build failure though, BurntSushi can't be loaded?

**Comment by tjann** [comment]
This started failing in https://github.com/datacommonsorg/data/pull/120 with the same BurntSushi error. I will first merge this and then see about fixing go CI.

I ran `git diff 12e468fb3d6a4870c96e70370b199988c2c0a63a` on current code and see no diffs.

**Comment by beets** [comment]
sgtm, though we should update settings so merge isn't allowed if datcom-ci is failing.

**Pull request merged**
