### PR TITLE
update OECD tl3 to have full data

### PR DESCRIPTION
**Pull request by hanlu09205**
Current, TL3 data is truncated per https://github.com/datacommonsorg/data/issues/369, and TL2 data only has year from 2001. 
725CUkMyZ3pyDJr
Instead, download ready-made file,
4ypzTDjF9RC9kfJ which could cover both TL2 & TL3, with a wider year range. 

For easy explanation what has been verified, I call the resolved MCF generated from ready-made file, new data. 

For check whether new data could replace current prod TL3 MCF, 
I have ran prod templateMCF+CSV vs new data
their convert CSV to MCF email: 
BtHfUfV6ZFvL98s
resolve MCF: same statvar, more obs nodes
4NvuViMDCwi5SxB

---
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/data/387)

Validation dashboard: 
BNTxqMYWhfyb5QY
Most counters are doing better. 

Also the missing Geelong data shows up. 
Geelong male: https://screenshot.googleplex.com/BRdXKfTKGU3xTKZ
Geelong female: https://screenshot.googleplex.com/8EU5R8yxCA85cTy

For checking whether new data could replace TL2. 
And I ran three validation pipelines. 
1) prod resolved MCF 
2) prod resolved MCF except TL3, add new data. 
3) prod resolved MCF except TL2 & TL3, add new data. 

Compare the first & third validation email results, they have almost the same counter values, except that some counters from the third email have a larger NumStats, which makes sense, as READY-Made file has full data, while original TL3 is truncated. 

Second validation has many duplicate obs values, see below. 
oh4nmxBLPfiyH6g
After fixing filtering POS and TL, duplicate obs improved: 
5N7LSJ6YcrFjKzd

Further investigation points out that the original downloaded TL2 CSV only has data back to 2001, 
725CUkMyZ3pyDJr, 
BstTKB5ncrSay5i
while new data traced back to 1995.
9iXYv5aSPqPbjQA
Other spot checks point to the same explanation. 
What's more, spot check validation results where obs_stat_inconsistent_values is true. 
Prod has flipped 2009 vs 2010 data, causing graph not smooth, while new data has smooth graph.
Sanity check, OECD data was inconsistent between READY-made file and TL2 population data. 
eg: 
prod
BGHyyWjK7W7qnQt 
vs new data
7kkdrjRGDeZjNLX
prod dc/p/kjjgcj7kqvh87 
uHgBA8GJhE6jwQu
vs new data
BUTK6UCNY2jeADe
Other than data, all data are consistent, per spot checks. 

Prashanth also help verify the duplicate problem with steps below
1. Used gqui to find distinct DCIDs.
gqui> from /cns/jv-d/home/datcom/import_server/internal/validate_prod_oecd_no_tl3_new_population/ValidationProto@100 SELECT JoinUniqueStrings(place_dcid) WHERE obs_stat_inconsistent_values = true
2. There were 16 of them. Copied them over to a file, ran this and looked at the names of these DCIDs (using API url below).
$ cat foo.txt | tr ',' '\n' | awk '{ printf "&dcids=%s", $1; }'
https://api.datacommons.org/node/property-values?property=name&dcids=country/CHL&dcids=wikidataId/Q16926&dcids=wikidataId/Q2109&dcids=wikidataId/Q2114&dcids=wikidataId/Q2120&dcids=wikidataId/Q2131&dcids=wikidataId/Q2133&dcids=wikidataId/Q2170&dcids=wikidataId/Q2176&dcids=wikidataId/Q2177&dcids=wikidataId/Q2178&dcids=wikidataId/Q2181&dcids=wikidataId/Q219458&dcids=wikidataId/Q3612&dcids=wikidataId/Q3871&dcids=wikidataId/Q684369
3. Looked at the names of the places, and googled ones I didn't know.

To answer question whether we are missing any <place-dcid>+<stat-var> in this new dataset. I did following calculation. 

awk 'BEGIN { FS = "," } ; { print substr($3,2,length($3)-2)"_"substr($5,2,length($5)-2) }; {!x[$0]++}'  REGION_DEMOGR_population_tl2.csv  > prod_tl2
sort -u prod_tl2_sort prod_tl2  

awk 'BEGIN { FS = "\t" } ; {print substr($3,2,length($3)-2)"_"substr($5,2,length($5)-2)}' ~/Downloads/REGION_DEMOGR-en.csv > new_data
sort -u new_data > new_data_sort

comm -13 <(sort -u new_data_sort) <(sort -u prod_tl2_sort)

This check if any  <place-dcid>+<stat-var> exist in TL2 missing from new data, and only CL16 is missing. 
 grep CL16 from  ~/Downloads/REGION_DEMOGR-en.csv  returns empty, which prove that. 
Added a manual curated CSV for this.

### CODE REVIEW

**Review by pradh — COMMENTED** [review]
> Geelong male: https://screenshot.googleplex.com/BRdXKfTKGU3xTKZ

Male by age-group: https://screenshot.googleplex.com/C7HkQHTvxqdKqtf

> Geelong female: https://screenshot.googleplex.com/8EU5R8yxCA85cTy
> Validation dashboard: https://screenshot.googleplex.com/5npt2vFQrVygujU
> 
> random prod data: https://screenshot.googleplex.com/5NLDHthLUQSh6Ur

This is Turkey, so unrelated to this dataset?  I think the only two age ranges showing up is because of timeline limitation: browser shows everything: https://screenshot.googleplex.com/8DUD9BkauM9MaXM

> This resolved MCF: https://datcom-browser-v3-staging.googleplex.com/kg?dcid=dc/p/ejx3718rpwse

**Comment by pradh** [comment]
Note sure if this will trigger a schedule, but I see:

  SCHEDULES=scripts/ourworldindata/covid19:OWID_COVID19

in your commit history...

**Review by hanlu09205 — COMMENTED** [review]
>  Re Turkey, I was trying to a random place spot check, see whether it matches prod. 

Re SCHEDULES, I don't why it's here... could be some git branch thing. 
I was planning to clean this when merge & squash. 

Re Male by age-group, what are you trying to say?
Besides, I clicked on the screenshot you sent, and then the link on the screenshot, it shows a graph of  https://screenshot.googleplex.com/BRdXKfTKGU3xTKZ, different from what you attached. 
Though from validation, I do see other age gap generated. 
from /cns/jv-d/home/datcom/import_server/internal/validate_oecd_tl3_v1/ValidationProto@100 WHERE place_dcid = "wikidataId/Q231765" 

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/387#-:-MS5BFNv8ityCVbBOer_:b-ex3stn)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @pradh)

___
*[scripts/oecd/regional_demography/README.md, line 20 at r5](https://reviewable.io/reviews/datacommonsorg/data/387#-MS53Cr7wvLudKTlc3JW-r5-20:-MS58XRUEef-q7OICXv_:b-3109xi) ([raw file](https://github.com/datacommonsorg/data/blob/4e998074604685c06471831e1bf7e86b0cb71658/scripts/oecd/regional_demography/README.md#L20)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

You could perhaps edit the Download URL section to add this note?
</blockquote></details>

How did u update the image? I was following https://stackoverflow.com/questions/61537403/how-to-host-image-at-https-user-images-githubusercontent-com-path-filename but the instruction for https://user-images.githubusercontent.com/ is not working. I only get something like https://github.com/hanlu09205/DC-images/blob/415fe5ac27084f7069ad6fac4aa9f662a1d4a608/.github/images/4ypzTDjF9RC9kfJ.png. 
___
*[scripts/oecd/regional_demography/population_tl3/preprocess_csv.py, line 23 at r5](https://reviewable.io/reviews/datacommonsorg/data/387#-MS53Cr7wvLudKTlc3JX-r5-23:-MS59O4oA9v39nZ6toOt:b-5yi5gh) ([raw file](https://github.com/datacommonsorg/data/blob/4e998074604685c06471831e1bf7e86b0cb71658/scripts/oecd/regional_demography/population_tl3/preprocess_csv.py#L23)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

As such this is reading the raw CSV file in this directory. Did you change it? If so, upload it (until we move to GCS)?

Any notes on how this csv differs from the one before?
</blockquote></details>

I added read me regarding the CSV. 
It's quite big. Since we are trying to reduce repro size, do we need to add it in the repository? I actually deleted the file in the PR. 
___
*[scripts/oecd/regional_demography/population_tl3/preprocess_csv.py, line 108 at r5](https://reviewable.io/reviews/datacommonsorg/data/387#-MS53Cr7wvLudKTlc3JX-r5-108:-MS59smC4AGeGsxFxlMj:brdd4ax) ([raw file](https://github.com/datacommonsorg/data/blob/4e998074604685c06471831e1bf7e86b0cb71658/scripts/oecd/regional_demography/population_tl3/preprocess_csv.py#L108)):*
> Count_Person_Female
Yes it shouldn't.

**Review by hanlu09205 — COMMENTED** [review]
I got SxS comparison with prod. 

Validation flume counter output something interesting. 

1) most counters are doing better except few ones. 
Spot check dc/p/cv7xpbkbhm146 and it does has holes. 

2) new MCF also has EurostatNuts2 count People
I checked the original CSV and it has TL1 & TL2. Also preprocessor doesn't do any filter for those TL1 & TL2, or Nuts2 & Nuts3, I left them as is. 
Do you see a problem here?
 
3) I am not exactly sure what is State_Person-count-measuredValue, this is other State_XXX is something new.
capacitor file is /cns/jv-d/home/datcom/import_server/internal/validate_oecd_tl3_v1/ValidationProto@100. 
https://dashboards.corp.google.com/_51d0e7ea_3666_4fe8_82a6_acbf24d2585f?p=CNSPATH:/cns/jv-d/home/datcom/import_server/internal/validate_oecd_tl3_v1/ValidationProto@100
Mind pointing where the counter name is formed and I could look into. 

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/387#-:-MS6G1H202kgjtGIZZ4y:bev923i)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @pradh)

___
*[scripts/oecd/regional_demography/README.md, line 20 at r5](https://reviewable.io/reviews/datacommonsorg/data/387#-MS53Cr7wvLudKTlc3JW-r5-20:-MS6FBOEDosbOLStdgMj:b-vf9gyi) ([raw file](https://github.com/datacommonsorg/data/blob/4e998074604685c06471831e1bf7e86b0cb71658/scripts/oecd/regional_demography/README.md#L20)):*
<details><summary><i>Previously, hanlu09205 wrote…</i></summary><blockquote>

How did u update the image? I was following https://stackoverflow.com/questions/61537403/how-to-host-image-at-https-user-images-githubusercontent-com-path-filename but the instruction for https://user-images.githubusercontent.com/ is not working. I only get something like https://github.com/hanlu09205/DC-images/blob/415fe5ac27084f7069ad6fac4aa9f662a1d4a608/.github/images/4ypzTDjF9RC9kfJ.png. 
</blockquote></details>

Done. 
For image, I update it in PR description, get a link, then use it in README...
___
*[scripts/oecd/regional_demography/population_tl3/preprocess_csv.py, line 23 at r5](https://reviewable.io/reviews/datacommonsorg/data/387#-MS53Cr7wvLudKTlc3JX-r5-23:-MS6FT3V6flyZruJJi2S:bi6ai1f) ([raw file](https://github.com/datacommonsorg/data/blob/4e998074604685c06471831e1bf7e86b0cb71658/scripts/oecd/regional_demography/population_tl3/preprocess_csv.py#L23)):*
<details><summary><i>Previously, hanlu09205 wrote…</i></summary><blockquote>

I added read me regarding the CSV. 
It's quite big. Since we are trying to reduce repro size, do we need to add it in the repository? I actually deleted the file in the PR. 
</blockquote></details>

Uploaded to datcom datcom-source-data bucket and update README.

**Review by pradh — CHANGES_REQUESTED** [review]
Thanks for the detailed screenshots!

RE: your questions

2. Good find.

    To confirm, did you run the current-prod validation with TL3 only or with everything? (Refer prod MCF: https://cnsviewer2.corp.google.com/cns/jv-d/home/datcom/v3_resolved_mcf/oecd/sharded/).

    We might want to confirm that the overlapping stats for a particular TL2 place, between this dataset and TL2 dataset, does not cause "DuplicateObsVal" errors.


3. The Key column is constructed in this script https://plx.corp.google.com/scripts2/script_5e._31ed56_0000_23c9_a2cc_001a113555ba.  It summarizes the group-by done: {placeType + popType + mprop + statType + cProps}.

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/387#-:-MS9E87A8KXz_757hB9r:b7lvvr3)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @hanlu09205)

___
*[scripts/oecd/regional_demography/README.md, line 20 at r5](https://reviewable.io/reviews/datacommonsorg/data/387#-MS53Cr7wvLudKTlc3JW-r5-20:-MS9_0Qp6BXbCGmNARuv:b-ucfknh) ([raw file](https://github.com/datacommonsorg/data/blob/4e998074604685c06471831e1bf7e86b0cb71658/scripts/oecd/regional_demography/README.md#L20)):*
<details><summary><i>Previously, hanlu09205 wrote…</i></summary><blockquote>

Done. 
For image, I update it in PR description, get a link, then use it in README...
</blockquote></details>

Thanks!
___
*[scripts/oecd/regional_demography/README.md, line 38 at r7](https://reviewable.io/reviews/datacommonsorg/data/387#-MS9_N-7DgRMAGVzL1-r:-MS9_N-7DgRMAGVzL1-s:bfydd6a) ([raw file](https://github.com/datacommonsorg/data/blob/f31c2449c67ea48d8d00655d89b294dda6c14dfb/scripts/oecd/regional_demography/README.md#L38)):*
> ```
> In each subdirectory, the source CSVs are saved as `REGION_DEMOGR_{subdirectory name}.csv`.
> ```
Update this?
___
*[scripts/oecd/regional_demography/population_tl3/preprocess_csv.py, line 23 at r5](https://reviewable.io/reviews/datacommonsorg/data/387#-MS53Cr7wvLudKTlc3JX-r5-23:-MS9_SPt0ipD5XU-4rTA:bbxtcr8) ([raw file](https://github.com/datacommonsorg/data/blob/4e998074604685c06471831e1bf7e86b0cb71658/scripts/oecd/regional_demography/population_tl3/preprocess_csv.py#L23)):*
<details><summary><i>Previously, hanlu09205 wrote…</i></summary><blockquote>

Uploaded to datcom datcom-source-data bucket and update README. 
</blockquote></details>

Thanks.  Then, we should either read from that path (using GCS APIs) or please add the command line to copy from there to local dir before running it under the "Generating Artifacts" section of the README.

To regenerate the data, we would ideally document all the commands needed.

**Review by hanlu09205 — COMMENTED** [review]
Thanks for the offline discussion, Prashanth!
I have updated the PR description, as well as the readme. 

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/387#-:-MSUw5VR2UfC-muTO7IY:b-78xkht)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @hanlu09205)

**Comment by pradh** [comment]
Thanks for the detailed note.  Its good that the new dataset has stats from 1990s.

> This proves that for the same TL2, for a given year, the stat-var have the same value.

If for the same year the values are the same then there will be a single Observation, and DuplicateObsVal shouldn't show up I think.

> To answer question whether we are missing any + in this new dataset. I did following calculation.

Good find that CL16 is missing.

Are there things that were missing in TL2 that you are improving with this PR, besides longer dates? (i.e., comm -23 ...)

Do the stat-vars match up for all non-CL16 places?

**Review by hanlu09205 — COMMENTED** [review]
Not sure what is "comm -23 ". Besides from the longer dates, for TL2, I don't think so. TL3 has data originally being truncated. 

For all non-CL16 places,  we are not missing any place+stat-vars pairs. 
For running "comm -13 <(sort -u new_data_sort) <(sort -u prod_tl2_sort)", I also got things below, but they are not population related. 
EL51_Thrace
JPC_Koshin
JPJ_Okinawa

Same thing for comparing new_data_sort with prod_tl3_sort. None missing piece is about population. 

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/387#-:-MSYpUou9lazqL-N39Uf:b-9qxrhz)* status: 0 of 13 files reviewed, 4 unresolved discussions (waiting on @hanlu09205 and @pradh)

___
*[scripts/oecd/regional_demography/README.md, line 38 at r7](https://reviewable.io/reviews/datacommonsorg/data/387#-MS9_N-7DgRMAGVzL1-r:-MSYtXON8yWBo6529Psw:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/f31c2449c67ea48d8d00655d89b294dda6c14dfb/scripts/oecd/regional_demography/README.md#L38)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> In each subdirectory, the source CSVs are saved as `REGION_DEMOGR_{subdirectory name}.csv`.
> ```
Update this?
</blockquote></details>

Done.
___
*[scripts/oecd/regional_demography/README.md, line 37 at r9](https://reviewable.io/reviews/datacommonsorg/data/387#-MSYtPle6rW-XY3Srdma:-MSYtPle6rW-XY3Srdmb:bebeieo) ([raw file](https://github.com/datacommonsorg/data/blob/c7dac02e0a35a87bed61e088c7986ee59f79367a/scripts/oecd/regional_demography/README.md#L37)):*
> In each subdirectory, the source CSVs are saved as `REGION_DEMOGR_{subdirectory name}.csv`.
___
*[scripts/oecd/regional_demography/population_tl3/preprocess_csv.py, line 23 at r5](https://reviewable.io/reviews/datacommonsorg/data/387#-MS53Cr7wvLudKTlc3JX-r5-23:-MSYtIJr6-lnmAkm4lz0:b-dlnt20) ([raw file](https://github.com/datacommonsorg/data/blob/4e998074604685c06471831e1bf7e86b0cb71658/scripts/oecd/regional_demography/population_tl3/preprocess_csv.py#L23)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

Thanks.  Then, we should either read from that path (using GCS APIs) or please add the command line to copy from there to local dir before running it under the "Generating Artifacts" section of the README.

To regenerate the data, we would ideally document all the commands needed.
</blockquote></details>

Updated.

**Review by pradh — CHANGES_REQUESTED** [review]
You did:
> comm -13 <(sort -u new_data_sort) <(sort -u prod_tl2_sort)

That's for stuff that's only in prod. I was asking for <place, stat-var-id> that's only in new_data_sort.

I'm still not clear on the duplicate obs vals, any comment on:

> If for the same year the values are the same then there will be a single Observation, and DuplicateObsVal shouldn't show up I think.

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/387#-:-MSZ-iUsC3BvUXjgZk1X:bxt7qqg)* status: 0 of 13 files reviewed, 5 unresolved discussions (waiting on @hanlu09205)

___
*[scripts/oecd/regional_demography/README.md, line 39 at r9](https://reviewable.io/reviews/datacommonsorg/data/387#-MSWPGaGA3NEhCATWcZq:-MSWPGaGA3NEhCATWcZr:bosvcs6) ([raw file](https://github.com/datacommonsorg/data/blob/c7dac02e0a35a87bed61e088c7986ee59f79367a/scripts/oecd/regional_demography/README.md#L39)):*
> ```
> small repository.
> ```

What is small repository?
___
*[scripts/oecd/regional_demography/README.md, line 52 at r10](https://reviewable.io/reviews/datacommonsorg/data/387#-MSZCd9QCo1V2U_K78tY:-MSZCd9QCo1V2U_K78tZ:b79rigb) ([raw file](https://github.com/datacommonsorg/data/blob/bbaa663c93ad2596527d354318763ba63b03ae2c/scripts/oecd/regional_demography/README.md#L52)):*
> ```
> To re-generate population cleaned CSV, copy its raw data to population directory, and run preprocess_csv.
> ```
cmd-line please?

(for the person regenerating stuff, it helps to make the instructions as simple as possible)
___
*[scripts/oecd/regional_demography/population_tl3/preprocess_csv.py, line 23 at r5](https://reviewable.io/reviews/datacommonsorg/data/387#-MS53Cr7wvLudKTlc3JX-r5-23:-MSZCu2kCIXfiy5yHchU:bwoozvq) ([raw file](https://github.com/datacommonsorg/data/blob/4e998074604685c06471831e1bf7e86b0cb71658/scripts/oecd/regional_demography/population_tl3/preprocess_csv.py#L23)):*
<details><summary><i>Previously, hanlu09205 wrote…</i></summary><blockquote>

Updated. 
</blockquote></details>

Missing cmd line?

**Review by hanlu09205 — COMMENTED** [review]
> new_data_sort
For duplicate obs vals, if the old data doesn't have 1985 and new data has 1985, then it will be marked as inconsistent. 
https://screenshot.googleplex.com/9iXYv5aSPqPbjQA
I don't see any for the same year, they have different value, except one is empty. 


Do you want the whole thing in new_data_sort but not in prod_tl2_sort?
What are you trying to prove before migration?
It has many more pairs as it has other non population data. 
However, preprocess would filter by VAR so that only population related var stayed. 

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/387#-:-MSZZt2c8bjPkO6RG4f7:b-bsqs9v)* status: 0 of 13 files reviewed, 5 unresolved discussions (waiting on @hanlu09205 and @pradh)

___
*[scripts/oecd/regional_demography/README.md, line 39 at r9](https://reviewable.io/reviews/datacommonsorg/data/387#-MSWPGaGA3NEhCATWcZq:-MSZQGga7ZJs4PSiDOZc:bk2ws2o) ([raw file](https://github.com/datacommonsorg/data/blob/c7dac02e0a35a87bed61e088c7986ee59f79367a/scripts/oecd/regional_demography/README.md#L39)):*
> duplicate
Repo doesn't contain huge CSV or cleaned CSV.
___
*[scripts/oecd/regional_demography/README.md, line 52 at r10](https://reviewable.io/reviews/datacommonsorg/data/387#-MSZCd9QCo1V2U_K78tY:-MSZZHNm-9f3MEMb2kAe:b-i6s3e3) ([raw file](https://github.com/datacommonsorg/data/blob/bbaa663c93ad2596527d354318763ba63b03ae2c/scripts/oecd/regional_demography/README.md#L52)):*
> ```
> To re-generate population cleaned CSV, copy its raw data to population directory, and run preprocess_csv.
> ``I have updated the README to avoid repeating same rhythm.
___
*[scripts/oecd/regional_demography/population_tl3/preprocess_csv.py, line 23 at r5](https://reviewable.io/reviews/datacommonsorg/data/387#-MS53Cr7wvLudKTlc3JX-r5-23:-MSZWZvvEyBci6Fi0Qmr:bfh3oje) ([raw file](https://github.com/datacommonsorg/data/blob/4e998074604685c06471831e1bf7e86b0cb71658/scripts/oecd/regional_demography/population_tl3/preprocess_csv.py#L23)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

Missing cmd line?
</blockquote></details>

I believe this one is documented in README?

**Review by hanlu09205 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/387)* status: 0 of 13 files reviewed, 5 unresolved discussions (waiting on @hanlu09205 and @pradh)

___
*[scripts/oecd/regional_demography/README.md, line 52 at r10](https://reviewable.io/reviews/datacommonsorg/data/387#-MSZCd9QCo1V2U_K78tY:-MSZbPQ59M_uWgNi_dZq:by750wf) ([raw file](https://github.com/datacommonsorg/data/blob/bbaa663c93ad2596527d354318763ba63b03ae2c/scripts/oecd/regional_demography/README.md#L52)):*
<details><summary><i>Previously, hanlu09205 wrote…</i></summary><blockquote>

> ```
> To re-generate population cleaned CSV, copy its raw data to population directory, and run preprocess_csv.
> ``I have updated the README to avoid repeating same rhythm.
</blockquote></details>

I have re-arranged some lines in README to avoid repeating rymthem.

**Review by pradh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/387)* status: 0 of 13 files reviewed, 7 unresolved discussions (waiting on @hanlu09205)

___
*[scripts/oecd/regional_demography/README.md, line 39 at r12](https://reviewable.io/reviews/datacommonsorg/data/387#-MSjDlygAeIQ8CBUmI3f:-MSjDlygAeIQ8CBUmI3g:b-qa461y) ([raw file](https://github.com/datacommonsorg/data/blob/6ac80f3bbc75a2b4cc076c4d6062ce1ae896df88/scripts/oecd/regional_demography/README.md#L39)):*
> ```
> at
> ```
nit: remove "at"
___
*[scripts/oecd/regional_demography/README.md, line 42 at r12](https://reviewable.io/reviews/datacommonsorg/data/387#-MSjE5duDOZDNcdEfEjh:-MSjE5duDOZDNcdEfEji:bvvzzvx) ([raw file](https://github.com/datacommonsorg/data/blob/6ac80f3bbc75a2b4cc076c4d6062ce1ae896df88/scripts/oecd/regional_demography/README.md#L42)):*
> ```Markdown
> To copy raw CSV into the population directory, run:
> ```bash
> gsutil cp gs://datcom-source-data/oecd/regional_demography/population/REGION_DEMOGR_population.csv
> ```

nit: does it not need destination?
```
gsutil cp X .
```
___
*[scripts/oecd/regional_demography/population/preprocess_csv.py, line 43 at r12](https://reviewable.io/reviews/datacommonsorg/data/387#-MSjFBWbEx_YqLpvxNHb:-MSjFBWbEx_YqLpvxNHc:b2vaaza) ([raw file](https://github.com/datacommonsorg/data/blob/6ac80f3bbc75a2b4cc076c4d6062ce1ae896df88/scripts/oecd/regional_demography/population/preprocess_csv.py#L43)):*
> ```
> df['TL'].isin(['1', '2', '3']
> ```
___
*[scripts/oecd/regional_demography/population/preprocess_csv.py, line 44 at r12](https://reviewable.io/reviews/datacommonsorg/data/387#-MSjFuqdCl61QWBpNmd6:-MSjFuqeDuR5zUS9AOuP:b-hwlqbx) ([raw file](https://github.com/datacommonsorg/data/blob/6ac80f3bbc75a2b4cc076c4d6062ce1ae896df88/scripts/oecd/regional_demography/population/preprocess_csv.py#L44)):*
> ```
> print(df)
> ```

remove? or add a --verbose flag
___
*[scripts/oecd/regional_demography/population/preprocess_csv.py, line 59 at r12](https://reviewable.io/reviews/datacommonsorg/data/387#-MSjFzMPA299RKnFjpsp:-MSjFzMPA299RKnFjpsq:b-uu1dn7) ([raw file](https://github.com/datacommonsorg/data/blob/6ac80f3bbc75a2b4cc076c4d6062ce1ae896df88/scripts/oecd/regional_demography/population/preprocess_csv.py#L59)):*
> ```
> print(df_cleaned)
> ```

remove or add a --verbose flag

**Pull request merged**
