### PR TITLE
India UDISE SchoolDropRate Dataset

### PR DESCRIPTION
**Pull request by thejeshgn**
Hi @pradh 

- Added base class to india_udise for common functionality reuse 
- Add udise_school_dropout_rate
- Downloaded the initial JSON files and generated the CSV

### TODO
- Download all the JSON files and generate the final CSV

If the code looks good, we can merge this PR as another PR dependent on this can we pushed. Just the data (Raw JSONs and Final CSV) can be pushed using another PR.

---
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/data/436)

### CODE REVIEW

**Comment by pradh** [comment]
Thanks for the PR.

Wow, there are 610 files here. Can we separate out the real data files (test_data is fine) in a separate PR from code? And does it make sense to merge the files to make them fewer?

**Review by pradh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/436)* status: 0 of 610 files reviewed, 6 unresolved discussions (waiting on @thejeshgn)

___
*[scripts/india_udise/common/base.py, line 14 at r1](https://reviewable.io/reviews/datacommonsorg/data/436#-Ma-4Esz5FE3GcpbBjFt:-Ma-4Esz5FE3GcpbBjFu:b6c3b8l) ([raw file](https://github.com/datacommonsorg/data/blob/83db19477a23b5a25539fc4bf6a4c1d9896a1859/scripts/india_udise/common/base.py#L14)):*
> ```
> import geography data
> ```
nit: more than just geo data?
___
*[scripts/india_udise/common/base.py, line 59 at r1](https://reviewable.io/reviews/datacommonsorg/data/436#-Ma-4PLs8akAYXB19buS:-Ma-4PLs8akAYXB19buT:b-lmjvcg) ([raw file](https://github.com/datacommonsorg/data/blob/83db19477a23b5a25539fc4bf6a4c1d9896a1859/scripts/india_udise/common/base.py#L59)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> YEAR_PERIOD_MAPPING = {
>     "2014-15": "2015-03",
>     "2015-16": "2016-03",
>     "2016-17": "2017-03",
>     "2017-18": "2018-03",
>     "2018-19": "2019-03"
> }
> ```
</details>


Should we have a function for this? So next year if we run it will just work without changing code?

```
def year_to_period(year):
  assert re.match(r'^[0-9]{4}-[0-9]{2}$', year), year
  return year[:2] + year[-2:] + '-03'
```
___
*[scripts/india_udise/common/base.py, line 207 at r1](https://reviewable.io/reviews/datacommonsorg/data/436#-Ma-6pMR3qwjxuQBOxuh:-Ma-6pMS5D1U4WuVsh_g:b-u34s37) ([raw file](https://github.com/datacommonsorg/data/blob/83db19477a23b5a25539fc4bf6a4c1d9896a1859/scripts/india_udise/common/base.py#L207)):*
> ```
> name_array.append(school_level)
> ```

nit: should we add to name_array only if we add to constraints_array? (here and elsewhere)
___
*[scripts/india_udise/common/base.py, line 281 at r1](https://reviewable.io/reviews/datacommonsorg/data/436#-Ma-8Lm-A0vHP4xRPPo5:-Ma-8Lm-A0vHP4xRPPo6:b-u2m3zj) ([raw file](https://github.com/datacommonsorg/data/blob/83db19477a23b5a25539fc4bf6a4c1d9896a1859/scripts/india_udise/common/base.py#L281)):*
> ```Python
>                 file_object.close()
>         else:
>             print("Data file: {data_file} doesn't exist".format(
> ```

Error out loudly?
___
*[scripts/india_udise/common/base.py, line 288 at r1](https://reviewable.io/reviews/datacommonsorg/data/436#-Ma-7b_LDHy5UrYDYIYJ:-Ma-7b_LDHy5UrYDYIYK:b-lbcu6g) ([raw file](https://github.com/datacommonsorg/data/blob/83db19477a23b5a25539fc4bf6a4c1d9896a1859/scripts/india_udise/common/base.py#L288)):*
> ```Python
>                   udise_state_code,
>                   udise_dist_code="none",
>                   udise_block_code="none"):
> ```

nit: For large functions docstring comments might be helpful.  Esp the fact that it downloads only if data doesn't exist locally.
___
*[scripts/india_udise/common/base.py, line 375 at r1](https://reviewable.io/reviews/datacommonsorg/data/436#-Ma-85vOA0ddipXMJQfT:-Ma-85vOA0ddipXMJQfU:bjofn2n) ([raw file](https://github.com/datacommonsorg/data/blob/83db19477a23b5a25539fc4bf6a4c1d9896a1859/scripts/india_udise/common/base.py#L375)):*
> ```
> self._load_geography()
> ```

Might be useful to note that _download_data depends on geos being loaded in self.states, etc.

**Review by thejeshgn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/436)* status: 0 of 616 files reviewed, 4 unresolved discussions (waiting on @pradh and @thejeshgn)

___
*[scripts/india_udise/common/base.py, line 59 at r1](https://reviewable.io/reviews/datacommonsorg/data/436#-Ma-4PLs8akAYXB19buS:-Ma-skgR18XFoLUWEoCo:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/83db19477a23b5a25539fc4bf6a4c1d9896a1859/scripts/india_udise/common/base.py#L59)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> YEAR_PERIOD_MAPPING = {
>     "2014-15": "2015-03",
>     "2015-16": "2016-03",
>     "2016-17": "2017-03",
>     "2017-18": "2018-03",
>     "2018-19": "2019-03"
> }
> ```

Should we have a function for this? So next year if we run it will just work without changing code?

```
def year_to_period(year):
  assert re.match(r'^[0-9]{4}-[0-9]{2}$', year), year
  return year[:2] + year[-2:] + '-03'
```
</blockquote></details>

Done.
___
*[scripts/india_udise/common/base.py, line 207 at r1](https://reviewable.io/reviews/datacommonsorg/data/436#-Ma-6pMR3qwjxuQBOxuh:-Ma-smiT-bPzT5N7qyri:b77dnpz) ([raw file](https://github.com/datacommonsorg/data/blob/83db19477a23b5a25539fc4bf6a4c1d9896a1859/scripts/india_udise/common/base.py#L207)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> name_array.append(school_level)
> ```

nit: should we add to name_array only if we add to constraints_array? (here and elsewhere)
</blockquote></details>

Will do this as a separate PR for all of them.
___
*[scripts/india_udise/common/base.py, line 281 at r1](https://reviewable.io/reviews/datacommonsorg/data/436#-Ma-8Lm-A0vHP4xRPPo5:-Ma-szG6CTnTLo8xpiDQ:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/83db19477a23b5a25539fc4bf6a4c1d9896a1859/scripts/india_udise/common/base.py#L281)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

Error out loudly?
</blockquote></details>

Done.
___
*[scripts/india_udise/common/base.py, line 375 at r1](https://reviewable.io/reviews/datacommonsorg/data/436#-Ma-85vOA0ddipXMJQfT:-Ma-t2Yo0VTmSUfrDuSa:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/83db19477a23b5a25539fc4bf6a4c1d9896a1859/scripts/india_udise/common/base.py#L375)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> self._load_geography()
> ```

Might be useful to note that _download_data depends on geos being loaded in self.states, etc.
</blockquote></details>

Done.

**Review by thejeshgn — COMMENTED** [review]
I have removed them currently. There is going to be a lot files. We can figure a way.

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/436#-:-Ma-tja89pV_eKg3aNhZ:b4tqyuj)* status: 0 of 616 files reviewed, 3 unresolved discussions (waiting on @pradh)

___
*[scripts/india_udise/common/base.py, line 59 at r1](https://reviewable.io/reviews/datacommonsorg/data/436#-Ma-4PLs8akAYXB19buS:-Ma-tw713ggL3ZcViEqa:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/83db19477a23b5a25539fc4bf6a4c1d9896a1859/scripts/india_udise/common/base.py#L59)):*
<details><summary><i>Previously, thejeshgn (Thejesh GN) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[scripts/india_udise/common/base.py, line 281 at r1](https://reviewable.io/reviews/datacommonsorg/data/436#-Ma-8Lm-A0vHP4xRPPo5:-Ma-tx8M0FxIR9YYmbqs:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/83db19477a23b5a25539fc4bf6a4c1d9896a1859/scripts/india_udise/common/base.py#L281)):*
<details><summary><i>Previously, thejeshgn (Thejesh GN) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[scripts/india_udise/common/base.py, line 375 at r1](https://reviewable.io/reviews/datacommonsorg/data/436#-Ma-85vOA0ddipXMJQfT:-Ma-txoRAlW4W5dYMfW3:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/83db19477a23b5a25539fc4bf6a4c1d9896a1859/scripts/india_udise/common/base.py#L375)):*
<details><summary><i>Previously, thejeshgn (Thejesh GN) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Review by thejeshgn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/436)* status: 0 of 616 files reviewed, 3 unresolved discussions (waiting on @pradh)

___
*[scripts/india_udise/common/base.py, line 59 at r1](https://reviewable.io/reviews/datacommonsorg/data/436#-Ma-4PLs8akAYXB19buS:-Ma-tZ-mE0jp8225C1_Y:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/83db19477a23b5a25539fc4bf6a4c1d9896a1859/scripts/india_udise/common/base.py#L59)):*
<details><summary><i>Previously, thejeshgn (Thejesh GN) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Review by thejeshgn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/436)* status: 0 of 616 files reviewed, 3 unresolved discussions (waiting on @pradh)

___
*[scripts/india_udise/common/base.py, line 59 at r1](https://reviewable.io/reviews/datacommonsorg/data/436#-Ma-4PLs8akAYXB19buS:-Ma-v-8Q-iSFcpjciHoJ:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/83db19477a23b5a25539fc4bf6a4c1d9896a1859/scripts/india_udise/common/base.py#L59)):*
<details><summary><i>Previously, thejeshgn (Thejesh GN) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[scripts/india_udise/common/base.py, line 281 at r1](https://reviewable.io/reviews/datacommonsorg/data/436#-Ma-8Lm-A0vHP4xRPPo5:-Ma-uza-4XPzLSmhJiod:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/83db19477a23b5a25539fc4bf6a4c1d9896a1859/scripts/india_udise/common/base.py#L281)):*
<details><summary><i>Previously, thejeshgn (Thejesh GN) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[scripts/india_udise/common/base.py, line 375 at r1](https://reviewable.io/reviews/datacommonsorg/data/436#-Ma-85vOA0ddipXMJQfT:-Ma-uysr56Ha1Nuzr9Dr:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/83db19477a23b5a25539fc4bf6a4c1d9896a1859/scripts/india_udise/common/base.py#L375)):*
<details><summary><i>Previously, thejeshgn (Thejesh GN) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Review by pradh — APPROVED** [review]
Thanks for all the changes!

**Pull request merged**
