### PR TITLE
Improve WDI and OECD READMEs

### PR DESCRIPTION
**Pull request by tjann**
Changes:

1. More detailed README
2. Add reasonable subdir structure to WDI folder
3. Cleanup the schema CSVs for WDI (remove combos like p0_placepg in favor of individual wave CSVs + a single combination of all currently in prod).

Reviewer note: the README diffs are large, you can consider just reading the proposed Markdown.

---
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/data/347)

### CODE REVIEW

**Review by hanlu09205 — COMMENTED** [review]
> Reviewed 1 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/347)* status: 1 of 23 files reviewed, 1 unresolved discussion (waiting on @hanlu09205, @pradh, and @tjann)

___
*[scripts/oecd/regional_demography/README.md, line 2 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPhDGg4EBCM-A9Dx720:-MPhDGg4EBCM-A9Dx721:bohj29b) ([raw file](https://github.com/datacommonsorg/data/blob/2a6e8a12a323e530a7fe4e3f725c80d5bd4b8996/scripts/oecd/regional_demography/README.md#L2)):*
> ```Markdown
> # Importing OECD Regional Demography Statistics Datasets Into Data Commons
> ```

Just a question to help me do the review, is there a way to review the README in the format that reader would see, instead of markup format with diff?

**Review by hanlu09205 — APPROVED** [review]
Stamp for unblocking submitting.

**Review by tjann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/347)* status: 1 of 23 files reviewed, 1 unresolved discussion (waiting on @hanlu09205 and @pradh)

___
*[scripts/oecd/regional_demography/README.md, line 2 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPhDGg4EBCM-A9Dx720:-MPjtIFJ1KqS-3hkxILs:b1gcxt3) ([raw file](https://github.com/datacommonsorg/data/blob/2a6e8a12a323e530a7fe4e3f725c80d5bd4b8996/scripts/oecd/regional_demography/README.md#L2)):*
<details><summary><i>Previously, hanlu09205 wrote…</i></summary><blockquote>

Just a question to help me do the review, is there a way to review the README in the format that reader would see, instead of markup format with diff?  
</blockquote></details>

You can look at e.g. https://github.com/datacommonsorg/data/blob/2a6e8a12a323e530a7fe4e3f725c80d5bd4b8996/scripts/oecd/regional_demography/README.md 

(https://screenshot.googleplex.com/483RApms6Hjwe2b)

**Review by pradh — APPROVED** [review]
> Reviewed 20 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/347)* status: 20 of 23 files reviewed, 19 unresolved discussions (waiting on @hanlu09205, @pradh, and @tjann)

*[a discussion](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk7I-N204l1iwLaF-0:-MPk7I-N204l1iwLaF-1:bce212p) (no related file):*
Thanks for the detailed READMEs!  This is super helpful!

(Feel free to defer comments to a followup PR if you like.)

---
___
*[scripts/oecd/regional_demography/README.md, line 23 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk24mV7eet_EIsjYig:-MPk24mWEW57Z_OkepbE:b-fhwcvd) ([raw file](https://github.com/datacommonsorg/data/blob/2a6e8a12a323e530a7fe4e3f725c80d5bd4b8996/scripts/oecd/regional_demography/README.md#L23)):*
> ```
> , which are documented inside Google. We are working on this
> ```

which we are working on, but ...
___
*[scripts/oecd/regional_demography/README.md, line 42 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk2al--ZsJU7BN25lQ:-MPk2al--ZsJU7BN25lR:b-c09il1) ([raw file](https://github.com/datacommonsorg/data/blob/2a6e8a12a323e530a7fe4e3f725c80d5bd4b8996/scripts/oecd/regional_demography/README.md#L42)):*
> ```
> `OECD_{subdirectory name}_stat_vars.mcf`
> ```

Are these and the WDI stat-vars all checked into piper's HumanReadableStatVars? Any time we make a change to the stat-vars or add a new stat-var we should update that? Might be worth adding an IMPORTANT note here and in WDI for that..
___
*[scripts/oecd/regional_demography/README.md, line 69 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk3K0YB3jTH2qKXoxZ:-MPk3K0YB3jTH2qKXox_:bu9udb1) ([raw file](https://github.com/datacommonsorg/data/blob/2a6e8a12a323e530a7fe4e3f725c80d5bd4b8996/scripts/oecd/regional_demography/README.md#L69)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> NOTE: this is already done and saved as [geos.csv](geos.csv).
> Only do this step if for some reason you feel that file needs updating.
> The xls file can be found in the info sidebar of the regional
> demographics dataset
> [page](https://stats.oecd.org/index.aspx?DataSetCode=REGION_DEMOGR)
> Export the "List of regions" sheet to CSV and save it in this directory.
> ```
</details>


This breaks the bulleted listing.  PTAL at https://github.com/datacommonsorg/data/blob/d18e1609bde9dd65f89c55e9dad588b6dec4836a/scripts/oecd/regional_demography/README.md
___
*[scripts/oecd/regional_demography/README.md, line 71 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk3nt85hk2druQ7pjI:-MPk3nt85hk2druQ7pjJ:bc2xexn) ([raw file](https://github.com/datacommonsorg/data/blob/2a6e8a12a323e530a7fe4e3f725c80d5bd4b8996/scripts/oecd/regional_demography/README.md#L71)):*
> ```
> in the info sidebar
> ```

nit: could you attach this screenshot https://screenshot.googleplex.com/4F5bJXpM7tqc7ba (assuming that's right)?
___
*[scripts/oecd/regional_demography/README.md, line 86 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk5bVkChrQUPXerTWt:-MPk5bVkChrQUPXerTWu:bmra4q) ([raw file](https://github.com/datacommonsorg/data/blob/2a6e8a12a323e530a7fe4e3f725c80d5bd4b8996/scripts/oecd/regional_demography/README.md#L86)):*
> ```
>   - Whether places are statistical, administrative, or
>     other regions are determined based on the
>     [OECD Regions at a Glance Documentation](https://www.oecd-ilibrary.org/sites/reg_glance-2016-en/1/3/1/index.html?itemId=/content/publication/reg_glance-2016-en&_csp_=c935435269a6598b27c5166da7d1ad21&itemIGO=oecd&itemContentType=book#ID1d8692e3-637b-4fdc-9097-245b08f9948a) and further Googling.
> ```

I was briefly trying to follow that and map it to what I think the code does in https://github.com/datacommonsorg/data/blob/d18e1609bde9dd65f89c55e9dad588b6dec4836a/scripts/oecd/regional_demography/clean_geos_csv.py#L33-L49

Feels a bit unsure... for e.g., AUS TL3 and HUN TL2 are listed as statistical regions but the code doesn't have that?
___
*[scripts/oecd/regional_demography/README.md, line 91 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk6E0G2fv2xzbR9355:-MPk6E0G2fv2xzbR9356:bseg3bm) ([raw file](https://github.com/datacommonsorg/data/blob/2a6e8a12a323e530a7fe4e3f725c80d5bd4b8996/scripts/oecd/regional_demography/README.md#L91)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> Note: After further investigation/improved understanding of the regions,
> update the special casing logic in this file.
> E.g. when we realize that Japan TL2 is actually not an AdminArea,
> but TL3 is, we should add a special case to append "AdministrativeArea1"
> to the place names of TL3 regions, not the TL2 regions.
> ```
</details>


Is this a TODO ?
___
*[scripts/oecd/regional_demography/README.md, line 107 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk6fCC7Fp4CQfQW2dO:-MPk6fCC7Fp4CQfQW2dP:b-5w18l) ([raw file](https://github.com/datacommonsorg/data/blob/2a6e8a12a323e530a7fe4e3f725c80d5bd4b8996/scripts/oecd/regional_demography/README.md#L107)):*
> ```
> [region_nuts_codes.json](region_nuts_codes.json)
> ```
How did we generate this?
___
*[scripts/oecd/regional_demography/README.md, line 112 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk6v7u00RUwT8r91K8:-MPk6v7u00RUwT8r91K9:b-80z19t) ([raw file](https://github.com/datacommonsorg/data/blob/2a6e8a12a323e530a7fe4e3f725c80d5bd4b8996/scripts/oecd/regional_demography/README.md#L112)):*
> ```Markdown
>   we **remove the later occurrences so that there is no conflict**.
> 
> Note: After further investigation/improved understanding of the regions,
> ```

TODO:
___
*[scripts/world_bank/wdi/README.md, line 23 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPjxYHKD6aauWIQDNWS:-MPjxYHKD6aauWIQDNWT:b-w6hxyn) ([raw file](https://github.com/datacommonsorg/data/blob/2a6e8a12a323e530a7fe4e3f725c80d5bd4b8996/scripts/world_bank/wdi/README.md#L23)):*
> ```Markdown
> ### Notes and Caveats
> 
> Data Commons has some legacy code inside Google that processes 13 WDI variables.
> ```

s/inside Google/not in github/
___
*[scripts/world_bank/wdi/README.md, line 40 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPjxmajDnx-6NK7WOBE:-MPjxmajDnx-6NK7WOBF:bfvmdre) ([raw file](https://github.com/datacommonsorg/data/blob/2a6e8a12a323e530a7fe4e3f725c80d5bd4b8996/scripts/world_bank/wdi/README.md#L40)):*
> ```
> estimated or standardized across data sources by the WDI.
> ```

Can you say more on what that means, perhaps with an example?
___
*[scripts/world_bank/wdi/README.md, line 70 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPjyg_fDIz4q73jQEHa:-MPjyg_gCrW3c7ZxYj3t:b-yoewf9) ([raw file](https://github.com/datacommonsorg/data/blob/2a6e8a12a323e530a7fe4e3f725c80d5bd4b8996/scripts/world_bank/wdi/README.md#L70)):*
> ```
> This is encodes
> ```
This encodes
___
*[scripts/world_bank/wdi/README.md, line 121 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPjzX1vBINiDMNjGCQr:-MPjzX1vBINiDMNjGCQs:b-b5x369) ([raw file](https://github.com/datacommonsorg/data/blob/2a6e8a12a323e530a7fe4e3f725c80d5bd4b8996/scripts/world_bank/wdi/README.md#L121)):*
> ```
> --fetchFromSource=<WHETHER TO RE-FETCH FROM WDI WEBSITE INSTEAD OF USING CHECKED-IN PREPROCESSED CSVS>
> ```

Is the value true or false?
___
*[scripts/world_bank/wdi/schema_csvs/README.md, line 10 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk-5nLEbfi4Fse7jA4:-MPk-5nLEbfi4Fse7jA5:b-j9z8o3) ([raw file](https://github.com/datacommonsorg/data/blob/2a6e8a12a323e530a7fe4e3f725c80d5bd4b8996/scripts/world_bank/wdi/schema_csvs/README.md#L10)):*
> ```
> Find the corresponding indicator code, name, and source.
> ```

It might be helpful to note where to find these, with a screenshot or something.
___
*[scripts/world_bank/wdi/schema_csvs/README.md, line 22 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk-I2t7dRIRhunDH0b:-MPk-I2t7dRIRhunDH0c:b-uef2wo) ([raw file](https://github.com/datacommonsorg/data/blob/2a6e8a12a323e530a7fe4e3f725c80d5bd4b8996/scripts/world_bank/wdi/schema_csvs/README.md#L22)):*
> ```
>    - Copy everything except the column headers
>      into [WorldBankIndicators_prod.csv](WorldBankIndicators_prod.csv).
> ```

Is there a command we can run to check p0, p1, placepg, etc. are in prod?

Not run this, but something like:

```
diff -c <(cat $(ls WorldBankIndicators_*.csv | grep -v WorldBankIndicators_prod.csv) | grep -v IndicatorCode,ConvertToInt | sort) <(cat WorldBankIndicators_prod.csv | grep -v IndicatorCode,ConvertToInt | sort)
```
___
*[scripts/world_bank/wdi/schema_csvs/README.md, line 36 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk0lHs12aFg7IYZE3A:-MPk0lHs12aFg7IYZE3B:b-niw6px) ([raw file](https://github.com/datacommonsorg/data/blob/2a6e8a12a323e530a7fe4e3f725c80d5bd4b8996/scripts/world_bank/wdi/schema_csvs/README.md#L36)):*
> ```
> IMPORTANT: Please help keep [WorldBankIndicators_prod.csv](WorldBankIndicators_prod.csv)
> up to date. Copy your rows over when you see your import prod.
> ```

This would be good to check (e.g., using the command above or something)
___
*[scripts/world_bank/wdi/schema_csvs/README.md, line 41 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk0sSz3o_PD-S-9qp6:-MPk0sSz3o_PD-S-9qp7:b-uczod6) ([raw file](https://github.com/datacommonsorg/data/blob/2a6e8a12a323e530a7fe4e3f725c80d5bd4b8996/scripts/world_bank/wdi/schema_csvs/README.md#L41)):*
> ```
> In progress variables:
> - [WorldBankIndicators_p1_modeling_issues.csv](WorldBankIndicators_p1_modeling_issues.csv): tjann found modeling issues with these variables from IanCostello's import and moved them out here.
> - [WorldBankIndicators_p1_placeobs.csv](WorldBankIndicators_p1_placeobs.csv): tjann realized that IanCostello's code in GitHub does not support Observations directly on places and thus moved those variables here.
> ```

What is the transition plan with these?
___
*[scripts/world_bank/wdi/schema_csvs/schema_template.csv, line 1 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk1T_22Ya-10oZFMkv:-MPk1T_22Ya-10oZFMkw:b-qr8tzt) ([raw file](https://github.com/datacommonsorg/data/blob/2a6e8a12a323e530a7fe4e3f725c80d5bd4b8996/scripts/world_bank/wdi/schema_csvs/schema_template.csv#L1)):*
> ```
> IndicatorCode,ConvertToInt,ExistingStatVar,IndicatorName,SourceNote,Source,
> ```

Might be good to document the non-schema columns in the README?

**Review by tjann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/347)* status: 20 of 23 files reviewed, 18 unresolved discussions (waiting on @hanlu09205, @pradh, and @tjann)

___
*[scripts/oecd/regional_demography/README.md, line 2 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPhDGg4EBCM-A9Dx720:-MQGZ3Ja6neyewVpY0GT:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/d18e1609bde9dd65f89c55e9dad588b6dec4836a/scripts/oecd/regional_demography/README.md#L2)):*
<details><summary><i>Previously, tjann (TJann) wrote…</i></summary><blockquote>

You can look at e.g. https://github.com/datacommonsorg/data/blob/2a6e8a12a323e530a7fe4e3f725c80d5bd4b8996/scripts/oecd/regional_demography/README.md 

(https://screenshot.googleplex.com/483RApms6Hjwe2b)
</blockquote></details>

Done.
___
*[scripts/oecd/regional_demography/README.md, line 23 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk24mV7eet_EIsjYig:-MQGZwTrEGK9adrvQYXF:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/d18e1609bde9dd65f89c55e9dad588b6dec4836a/scripts/oecd/regional_demography/README.md#L23)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> , which are documented inside Google. We are working on this
> ```

which we are working on, but ...
</blockquote></details>

Done.
___
*[scripts/oecd/regional_demography/README.md, line 42 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk2al--ZsJU7BN25lQ:-MQG_er75ZiyzGksblGL:b87qx64) ([raw file](https://github.com/datacommonsorg/data/blob/d18e1609bde9dd65f89c55e9dad588b6dec4836a/scripts/oecd/regional_demography/README.md#L42)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> `OECD_{subdirectory name}_stat_vars.mcf`
> ```

Are these and the WDI stat-vars all checked into piper's HumanReadableStatVars? Any time we make a change to the stat-vars or add a new stat-var we should update that? Might be worth adding an IMPORTANT note here and in WDI for that..
</blockquote></details>

Thanks for pointing this out. I'm leaving a note here to tell the GH users to contact DC. There's already a comment at the top of that file.
___
*[scripts/oecd/regional_demography/README.md, line 69 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk3K0YB3jTH2qKXoxZ:-MQGa5oz9M1PAnNL2N3O:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/d18e1609bde9dd65f89c55e9dad588b6dec4836a/scripts/oecd/regional_demography/README.md#L69)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> NOTE: this is already done and saved as [geos.csv](geos.csv).
> Only do this step if for some reason you feel that file needs updating.
> The xls file can be found in the info sidebar of the regional
> demographics dataset
> [page](https://stats.oecd.org/index.aspx?DataSetCode=REGION_DEMOGR)
> Export the "List of regions" sheet to CSV and save it in this directory.
> ```

This breaks the bulleted listing.  PTAL at https://github.com/datacommonsorg/data/blob/d18e1609bde9dd65f89c55e9dad588b6dec4836a/scripts/oecd/regional_demography/README.md
</blockquote></details>

Done.
___
*[scripts/oecd/regional_demography/README.md, line 71 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk3nt85hk2druQ7pjI:-MQGaNyJCy5I8ruMSU0a:bd4p2eo) ([raw file](https://github.com/datacommonsorg/data/blob/d18e1609bde9dd65f89c55e9dad588b6dec4836a/scripts/oecd/regional_demography/README.md#L71)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> in the info sidebar
> ```

nit: could you attach this screenshot https://screenshot.googleplex.com/4F5bJXpM7tqc7ba (assuming that's right)?
</blockquote></details>

Done, I refrained from attaching googleplex screenshots, but I guess it's ok
___
*[scripts/oecd/regional_demography/README.md, line 86 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk5bVkChrQUPXerTWt:-MQGab7s4n3ah02v09aP:byqw7s5) ([raw file](https://github.com/datacommonsorg/data/blob/d18e1609bde9dd65f89c55e9dad588b6dec4836a/scripts/oecd/regional_demography/README.md#L86)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
>   - Whether places are statistical, administrative, or
>     other regions are determined based on the
>     [OECD Regions at a Glance Documentation](https://www.oecd-ilibrary.org/sites/reg_glance-2016-en/1/3/1/index.html?itemId=/content/publication/reg_glance-2016-en&_csp_=c935435269a6598b27c5166da7d1ad21&itemIGO=oecd&itemContentType=book#ID1d8692e3-637b-4fdc-9097-245b08f9948a) and further Googling.
> ```

I was briefly trying to follow that and map it to what I think the code does in https://github.com/datacommonsorg/data/blob/d18e1609bde9dd65f89c55e9dad588b6dec4836a/scripts/oecd/regional_demography/clean_geos_csv.py#L33-L49

Feels a bit unsure... for e.g., AUS TL3 and HUN TL2 are listed as statistical regions but the code doesn't have that?
</blockquote></details>

We could add those. I didn't because they are Euro places which would be scrapped in favor of NUTS anyway (and NUTS is actually Nomenclature of Territorial Units for Statistics) in clean_geos_resolved_to_dict.py. I'll make a note in the code.
___
*[scripts/oecd/regional_demography/README.md, line 91 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk6E0G2fv2xzbR9355:-MQGc-4b05nDXGKm6AAB:baq1snj) ([raw file](https://github.com/datacommonsorg/data/blob/d18e1609bde9dd65f89c55e9dad588b6dec4836a/scripts/oecd/regional_demography/README.md#L91)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> Note: After further investigation/improved understanding of the regions,
> update the special casing logic in this file.
> E.g. when we realize that Japan TL2 is actually not an AdminArea,
> but TL3 is, we should add a special case to append "AdministrativeArea1"
> to the place names of TL3 regions, not the TL2 regions.
> ```

Is this a TODO ?
</blockquote></details>

yes, indicated, thanks!
___
*[scripts/oecd/regional_demography/README.md, line 107 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk6fCC7Fp4CQfQW2dO:-MQGc1XWB60TaH9Ta1vx:b-89kfvn) ([raw file](https://github.com/datacommonsorg/data/blob/d18e1609bde9dd65f89c55e9dad588b6dec4836a/scripts/oecd/regional_demography/README.md#L107)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> [region_nuts_codes.json](region_nuts_codes.json)
> ```
How did we generate this?
</blockquote></details>

I got this from Fran
___
*[scripts/oecd/regional_demography/README.md, line 112 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk6v7u00RUwT8r91K8:-MQGcHu-3pUBxIBU7ugg:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/d18e1609bde9dd65f89c55e9dad588b6dec4836a/scripts/oecd/regional_demography/README.md#L112)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

TODO:
</blockquote></details>

Done.
___
*[scripts/world_bank/wdi/README.md, line 23 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPjxYHKD6aauWIQDNWS:-MQGcRv6AgPDJtdLnMZM:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/d18e1609bde9dd65f89c55e9dad588b6dec4836a/scripts/world_bank/wdi/README.md#L23)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

s/inside Google/not in github/
</blockquote></details>

Done.
___
*[scripts/world_bank/wdi/README.md, line 40 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPjxmajDnx-6NK7WOBE:-MQGhyOuAXwkSTPRKo81:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/d18e1609bde9dd65f89c55e9dad588b6dec4836a/scripts/world_bank/wdi/README.md#L40)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> estimated or standardized across data sources by the WDI.
> ```

Can you say more on what that means, perhaps with an example?
</blockquote></details>

Done.
___
*[scripts/world_bank/wdi/README.md, line 70 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPjyg_fDIz4q73jQEHa:-MQGi09RA3s3VaKj1Plh:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/d18e1609bde9dd65f89c55e9dad588b6dec4836a/scripts/world_bank/wdi/README.md#L70)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> This is encodes
> ```
This encodes
</blockquote></details>

Done.
___
*[scripts/world_bank/wdi/README.md, line 121 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPjzX1vBINiDMNjGCQr:-MQGi7ABBoKSH0NlDV7W:b2nhswy) ([raw file](https://github.com/datacommonsorg/data/blob/d18e1609bde9dd65f89c55e9dad588b6dec4836a/scripts/world_bank/wdi/README.md#L121)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> --fetchFromSource=<WHETHER TO RE-FETCH FROM WDI WEBSITE INSTEAD OF USING CHECKED-IN PREPROCESSED CSVS>
> ```

Is the value true or false?
</blockquote></details>

Yes
___
*[scripts/world_bank/wdi/schema_csvs/README.md, line 10 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk-5nLEbfi4Fse7jA4:-MQGj7YDD0uL1famrg23:boafihv) ([raw file](https://github.com/datacommonsorg/data/blob/d18e1609bde9dd65f89c55e9dad588b6dec4836a/scripts/world_bank/wdi/schema_csvs/README.md#L10)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> Find the corresponding indicator code, name, and source.
> ```

It might be helpful to note where to find these, with a screenshot or something.
</blockquote></details>

I'm not sure how Ian got the full CSV, but I'm dropping a link to find all indicators.
___
*[scripts/world_bank/wdi/schema_csvs/README.md, line 22 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk-I2t7dRIRhunDH0b:-MQGjqT8AiRKUMddNrIC:bngxqnu) ([raw file](https://github.com/datacommonsorg/data/blob/d18e1609bde9dd65f89c55e9dad588b6dec4836a/scripts/world_bank/wdi/schema_csvs/README.md#L22)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
>    - Copy everything except the column headers
>      into [WorldBankIndicators_prod.csv](WorldBankIndicators_prod.csv).
> ```

Is there a command we can run to check p0, p1, placepg, etc. are in prod?

Not run this, but something like:

```
diff -c <(cat $(ls WorldBankIndicators_*.csv | grep -v WorldBankIndicators_prod.csv) | grep -v IndicatorCode,ConvertToInt | sort) <(cat WorldBankIndicators_prod.csv | grep -v IndicatorCode,ConvertToInt | sort)
```
</blockquote></details>

Did not have one, prod I made just for this PR to make things more clear. I will leave that for future work as it doesn't work with the current files.
___
*[scripts/world_bank/wdi/schema_csvs/README.md, line 41 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk0sSz3o_PD-S-9qp6:-MQGk4IUD4S5mTsSP_nN:bqv6xor) ([raw file](https://github.com/datacommonsorg/data/blob/d18e1609bde9dd65f89c55e9dad588b6dec4836a/scripts/world_bank/wdi/schema_csvs/README.md#L41)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> In progress variables:
> - [WorldBankIndicators_p1_modeling_issues.csv](WorldBankIndicators_p1_modeling_issues.csv): tjann found modeling issues with these variables from IanCostello's import and moved them out here.
> - [WorldBankIndicators_p1_placeobs.csv](WorldBankIndicators_p1_placeobs.csv): tjann realized that IanCostello's code in GitHub does not support Observations directly on places and thus moved those variables here.
> ```

What is the transition plan with these?
</blockquote></details>

P1 in general was not a high priority for DC, so I think this can just stay unless needed.
___
*[scripts/world_bank/wdi/schema_csvs/schema_template.csv, line 1 at r1](https://reviewable.io/reviews/datacommonsorg/data/347#-MPk1T_22Ya-10oZFMkv:-MQGkmndEG_WU4GEqgs9:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/d18e1609bde9dd65f89c55e9dad588b6dec4836a/scripts/world_bank/wdi/schema_csvs/schema_template.csv#L1)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> IndicatorCode,ConvertToInt,ExistingStatVar,IndicatorName,SourceNote,Source,
> ```

Might be good to document the non-schema columns in the README?
</blockquote></details>

Done.

**Pull request merged**
