### PR TITLE
Rerun OECD with latest placeid2dcid mappings.

### PR DESCRIPTION
**Pull request by tjann**

### CODE REVIEW

**Comment by tjann** [comment]
Screen Shot 2020-09-02 at 12 54 08 PM
Here is the first validation. 4 more are coming, but I'll update them in the internal bug/cl.

**Comment by pradh** [comment]
How easy/hard is it to re-run the diff stats you did last time?

I see both wins and losses (esp around nuts), might help to get a sense for whether it overall got better or worse.

**Review by pradh — APPROVED** [review]

**Comment by tjann** [comment]
@pradh I sent you #291 to help with the resolution tracking (from the go resolution library that uses placeid2dcid mappings).

The final mapping for OECD hard codes NUTS codes (among other special cases we can bootstrap from the original OECD Region ID). I inspected the final mapping--most of them seem to be:

1. Replacing geoNames with wikidata
2. Replace iso codes for sub-country level with wikidata (did these mostly come from geoNames?)
3. New mappings (improvements)
4. A few dropped mappings (~6).

I will leave this PR open for now but will copy over the files in time for rollout tonight.

**Comment by tjann** [comment]
DO NOT MERGE until #291 is merged, and regenerate the stats for this PR.

**Comment by pradh** [comment]
> @pradh I sent you #291 to help with the resolution tracking (from the go resolution library that uses placeid2dcid mappings).
> 
> The final mapping for OECD hard codes NUTS codes (among other special cases we can bootstrap from the original OECD Region ID). I inspected the final mapping--most of them seem to be:
> 
> 1. Replacing geoNames with wikidata
> 2. Replace iso codes for sub-country level with wikidata (did these mostly come from geoNames?)

These are expected.

> 3. New mappings (improvements)
> 4. A few dropped mappings (~6).

Thanks. I was curious about the counts really (before vs. after: count of mappings total/by-namespace, errors by type). So guess I'll wait for diffs on stats.txt?

**Review by pradh — APPROVED** [review]

**Pull request merged**
