### PR TITLE
Fix: Add new isoCode for Dadra and Nagar Haveli and Daman and Diu

### PR DESCRIPTION
**Pull request by thejeshgn**
- No change for current data sets
- For future use

### CODE REVIEW

**Review by pradh — APPROVED** [review]
We might need to regenerate the CSVs with this fix?

**Comment by thejeshgn** [comment]
>> We might need to regenerate the CSVs with this fix?
Not as of now.

**Review by pradh — APPROVED** [review]

**Comment by shifucun** [comment]
Can this PR be merged?

**Comment by thejeshgn** [comment]
@shifucun yes @pradh

**Comment by thejeshgn** [comment]
@pradh @shifucun let this [PR](https://github.com/datacommonsorg/data/pull/465) get merged first. I can optimise this PR.

**Pull request merged**
