### PR TITLE
Update Manifesting Artifacts section of Life of a Dataset document

### PR DESCRIPTION
**Pull request by lucy-kind**
Update KG --> Data Commons Graph and change final punctuation of sentence

### CODE REVIEW

**Review by beets — APPROVED** [review]
thanks! though there was also a second file that needed a similar update?

**Comment by lucy-kind** [comment]
Which file? afaict both your comments refer to the same sentence in one
file that was added from a feedback comment. Happy to change it elsewhere
if it needs it!

**Comment by beets** [comment]
The other comment is here (for representing_statistics.md): https://github.com/datacommonsorg/data/pull/790/files/400e382f17725252fb951d2872c1e41719075cf9#diff-ed358a30d6a86c65595ceca600f0a15ceee36e6da76705b031bdb86fc0f15071

**Comment by lucy-kind** [comment]
Oh nice catch! Updated :)

**Review by beets — APPROVED** [review]
thanks!

**Pull request merged**
