### PR TITLE
Fbi crime rewrite

### PR DESCRIPTION
**Pull request by hanlu09205**
The PR includes 
1) 2008 to 2019 FRI Offenses Known to Law Enforcement tables URL 
2) Branch files under google3/datacommons/mcf/crime to github
3) Clean CSV, including 
 - add 2nd rape column when needed, 
 - add population column if missing
 - remove duplicate entries under 2019
 - and etc
 4) logic to convert to city MCF file
 
Will follow up with 
- add test 
- remote MCF logic and add TMCF logic 
- add country support

Want to get the first PR in, and then iterate over.

---
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/data/388)

### CODE REVIEW

**Review by pradh — COMMENTED** [review]
Could you add a README please? Could you please indicate which file is newly added vs. ported from the existing one in g3 so its easier to review?

**Comment by pradh** [comment]
Adding @tjann who has some pending Crime stuff going.

tjann: don't feel obliged to review, but in case you were curious and wanted a glance :)

**Comment by hanlu09205** [comment]
> Could you add a README please? Could you please indicate which file is newly added vs. ported from the existing one in g3 so its easier to review?

Yes, adding README. 
Except preprocess.py branched from datacommons/import/crime/pre_process.py
Everything else are branched from google3/datacommons/mcf/crime.
Do you want those information in the README?

However, I have touched all the python files, but not .csv files. Since those python file assume certain input files, which are different from what the code grabs from Web.

**Comment by pradh** [comment]
> > Could you add a README please? Could you please indicate which file is newly added vs. ported from the existing one in g3 so its easier to review?
> 
> Yes, adding README.
> Except preprocess.py branched from datacommons/import/crime/pre_process.py
> Everything else are branched from google3/datacommons/mcf/crime.
> Do you want those information in the README?
> 
> However, I have touched all the python files, but not .csv files. Since those python file assume certain input files, which are different from what the code grabs from Web.

Thanks.

Since we're generating this with new code, we should have a list of steps to validate this against what's already in prod. Something like: https://screenshot.googleplex.com/Tct7enQa5eCeSXv

Also, this might be a good time to add some tests :)

**Comment by hanlu09205** [comment]
> > > Could you add a README please? Could you please indicate which file is newly added vs. ported from the existing one in g3 so its easier to review?
> > 
> > 
> > Yes, adding README.
> > Except preprocess.py branched from datacommons/import/crime/pre_process.py
> > Everything else are branched from google3/datacommons/mcf/crime.
> > Do you want those information in the README?
> > However, I have touched all the python files, but not .csv files. Since those python file assume certain input files, which are different from what the code grabs from Web.
> 
> Thanks.
> 
> Since we're generating this with new code, we should have a list of steps to validate this against what's already in prod. Something like: https://screenshot.googleplex.com/Tct7enQa5eCeSXv
> 
> Also, this might be a good time to add some tests :)

Created doc https://docs.google.com/document/d/1Rr3Y1stgNF67cAvkXmmYJVgkEnvwGnZbB7-Z45o3kk8/edit#heading=h.uudtym8swmf1 and will follow the example and update the doc along the way. 
Right now, I am still at the clean CSV and output TMCF stage. 

Also add test as well as TODO.

**Review by tjann — COMMENTED** [review]
This looks like a huge improvement @hanlu09205 !  Nice choice on using pandas to parse the xls files. I won't explicitly review, but let me know if you have any questions.

**Review by pradh — APPROVED** [review]
Nicely done!

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/388#-:-MSTX6sN5M3ymjpPNJs3:b-ao1qb6)* status: 0 of 10 files reviewed, 12 unresolved discussions (waiting on @hanlu09205)

___
*[scripts/fbi/crime/geocode_cities.py, line 3 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTT78i-yRIsCt-Vgmr:-MSTT78i-yRIsCt-Vgms:b-rjk85q) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/geocode_cities.py#L3)):*
> ```
> Map cities to the corresponding geocodes.
> ```

I was reviewing it by comparing to datacommons/mcf/crime/geocode_cities.py.  Are the deleted functions not needed or is the functionality included elsewhere?
___
*[scripts/fbi/crime/geocode_cities.py, line 24 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTSSXg1JbcJNfplF75:-MSTSSXg1JbcJNfplF76:b-m789sz) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/geocode_cities.py#L24)):*
> ```
>     new_name = name
>     # Remove any trailing digit due to footnote
>     new_name = new_name.lower().strip()
> ```
new_name = name.lower().strip()
___
*[scripts/fbi/crime/geocode_cities.py, line 27 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTSQRn8iJJDl90eb1-:-MSTSQRn8iJJDl90eb10:bahezv6) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/geocode_cities.py#L27)):*
> ```
>     # if state in set(['pa', 'mi']):
>     # new_name = re.sub('town$', '', name).strip()
> ```
Remove?
___
*[scripts/fbi/crime/geocode_cities.py, line 39 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTSjPp8ITkKpxBjo0h:-MSTSjPp8ITkKpxBjo0i:bg0yprh) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/geocode_cities.py#L39)):*
> ```
>         f = float(f)
>         f = int(f)
> ```

comment why float(f) is needed
___
*[scripts/fbi/crime/geocode_cities.py, line 77 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTTYX08Iizixgf4IF1:-MSTTYX08Iizixgf4IF2:b-fbjq66) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/geocode_cities.py#L77)):*
> ```
> def update_crime_geocode(crime, geo_codes, found_set, cities_not_found_set):
> ```

This looks like an exported func, add docstring?

Make the other functions local by prefixing '_' ?
___
*[scripts/fbi/crime/preprocess.py, line 65 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTUUsT05Rd2Shi9yYH:-MSTUUsT05Rd2Shi9yYI:b-ozjopy) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/preprocess.py#L65)):*
<details><summary><i alt="summary">Quoted 15 lines of code…</i></summary>

> ```
> YEAR_TO_URL = {
>     '2019':
>         'https://ucr.fbi.gov/crime-in-the-u.s/2019/crime-in-the-u.s.-2019/tables/table-8/table-8.xls',
>     # '2018': 'https://ucr.fbi.gov/crime-in-the-u.s/2018/crime-in-the-u.s.-2018/tables/table-8/table-8.xls',
>     # '2017': 'https://ucr.fbi.gov/crime-in-the-u.s/2017/crime-in-the-u.s.-2017/tables/table-8/table-8.xls',
>     # '2016': 'https://ucr.fbi.gov/crime-in-the-u.s/2016/crime-in-the-u.s.-2016/tables/table-8/table-8.xls',
>     # '2015': 'https://ucr.fbi.gov/crime-in-the-u.s/2015/crime-in-the-u.s.-2015/tables/table-8/table_8_offenses_known_to_law_enforcement_by_state_by_city_2015.xls',
>     # '2014': 'https://ucr.fbi.gov/crime-in-the-u.s/2014/crime-in-the-u.s.-2014/tables/table-8/Table_8_Offenses_Known_to_Law_Enforcement_by_State_by_City_2014.xls',
>     # '2013': 'https://ucr.fbi.gov/crime-in-the-u.s/2013/crime-in-the-u.s.-2013/tables/table-8/table_8_offenses_known_to_law_enforcement_by_state_by_city_2013.xls',
>     # '2012': 'https://ucr.fbi.gov/crime-in-the-u.s/2012/crime-in-the-u.s.-2012/tables/8tabledatadecpdf/table_8_offenses_known_to_law_enforcement_by_state_by_city_2012.xls',
>     # '2011': 'https://ucr.fbi.gov/crime-in-the-u.s/2011/crime-in-the-u.s.-2011/tables/table_8_offenses_known_to_law_enforcement_by_state_by_city_2011.xls',
>     # '2010': 'https://ucr.fbi.gov/crime-in-the-u.s/2010/crime-in-the-u.s.-2010/tables/10tbl08.xls',
>     # '2009': 'https://www2.fbi.gov/ucr/cius2009/data/documents/09tbl08.xls',
>     # '2008': 'https://www2.fbi.gov/ucr/cius2008/data/documents/08tbl08.xls',
> }
> ```
</details>

Can we keep the map, and take the year as arg?  Manual code change is more error-prone
___
*[scripts/fbi/crime/preprocess.py, line 103 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTUepA3P2Qcdp_og4A:-MSTUepA3P2Qcdp_og4B:b27s2yr) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/preprocess.py#L103)):*
> ```Python
> 
> # When there is two entries for the same city, skip the one with wrong population data.
> def _shouldSkipSpecialLine(year, field):
> ```

nit: use snake case consistently?
___
*[scripts/fbi/crime/preprocess.py, line 299 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTVz9IDd2hglqlZDRZ:-MSTVz9IDd2hglqlZDR_:b-4xo36k) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/preprocess.py#L299)):*
> ```
>     update_and_calculate_crime_csv(geo_codes, '2019_cleaned.csv',
>                                    '2019_calculated.csv')
> ```

Wondering why aren't we calling this in the loop for every year?
___
*[scripts/fbi/crime/preprocess_test.py, line 32 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTWHFmAjFUzGco49Rb:-MSTWHFnBH2k_VumYwC4:bnnergi) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/preprocess_test.py#L32)):*
> ```
> 'cleaned_data_basic.csv'
> ```

Wondering why not take this CSV as input, run update_and_calculate_crime_csv and validate geocodes e2e2?
___
*[scripts/fbi/crime/README.md, line 3 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTQrB1ECcp8bxLsAdv:-MSTQrB1ECcp8bxLsAdw:b-rpfwtt) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/README.md#L3)):*
> ```
> https://ucr.fbi.gov/crime-in-the-u.s)
> ```

Also consider including direct link to the CSV files.
___
*[scripts/fbi/crime/README.md, line 16 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTQzNB6miHqt37biLh:-MSTQzNB6miHqt37biLi:b-fgbb45) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/README.md#L16)):*
> ```
> We blindly add one column with value 1.·
> ```

This value is not used right?
___
*[scripts/fbi/crime/README.md, line 17 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTR3-zC5AIz_ey81-j:-MSTR3-zC5AIz_ey81-k:bot8apn) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/README.md#L17)):*
> ```
> For duplicate city data, we remove the one with wrong population data.
> ```
How do we check "wrong population"?

**Review by hanlu09205 — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/388#-:-MSTsPVD3Z1vulQLDVva:b-hlcaav)* status: 0 of 10 files reviewed, 11 unresolved discussions (waiting on @pradh)

___
*[scripts/fbi/crime/geocode_cities.py, line 3 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTT78i-yRIsCt-Vgmr:-MSTiNCz6kSs4mfcq1N-:bxfz32u) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/geocode_cities.py#L3)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> Map cities to the corresponding geocodes.
> ```

I was reviewing it by comparing to datacommons/mcf/crime/geocode_cities.py.  Are the deleted functions not needed or is the functionality included elsewhere?
</blockquote></details>

They are not needed for the current PR. 

If they needed later, I will add them.  Otherwise, they are added, but no test coverage, neither any use of them. Later I have to delete them again.
___
*[scripts/fbi/crime/geocode_cities.py, line 24 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTSSXg1JbcJNfplF75:-MSTilEJE_eJjEEq-vSS:bvdf6n1) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/geocode_cities.py#L24)):*
> new_name = new_name.lower().strip()
Done.
___
*[scripts/fbi/crime/geocode_cities.py, line 27 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTSQRn8iJJDl90eb1-:-MSTimrF4ik-wYAdQMLM:b8lw1ak) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/geocode_cities.py#L27)):*
>  if state in set(['pa', 'mi']):
I added a TODO to remove it later. 
I am not sure whether they were added back then. Maybe some year has such a problem. Leave it for now. 
___
*[scripts/fbi/crime/geocode_cities.py, line 39 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTSjPp8ITkKpxBjo0h:-MSTjeMo42x6C5IhOHz2:bpmu0ua) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/geocode_cities.py#L39)):*
> f = int(f)
Done.
___
*[scripts/fbi/crime/geocode_cities.py, line 77 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTTYX08Iizixgf4IF1:-MSTnsmG-0b_5PsTIMQ3:bjhvd2c) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/geocode_cities.py#L77)):*
> update_crime_geocode
Done.
___
*[scripts/fbi/crime/preprocess.py, line 65 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTUUsT05Rd2Shi9yYH:-MSTo3nQAsS8-C_jlbdR:btcnun9) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/preprocess.py#L65)):*
> ```
> YEAR_TO_URL = {
> ```
I didn't follow. 
The reason I comment out all other Years is because after some change, I didn't run the code over those years. 
Don't want to introduce to many changes to this cl. 
Let me left a TODO here. 
___
*[scripts/fbi/crime/preprocess.py, line 103 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTUepA3P2Qcdp_og4A:-MSTqc0i-tRScJJXctHp:b-j36x2l) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/preprocess.py#L103)):*
> use snake case consistently?
Done. Also updated isDigit
___
*[scripts/fbi/crime/preprocess.py, line 299 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTVz9IDd2hglqlZDRZ:-MSTqixlDgt3TnT47_hs:b5ry54y) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/preprocess.py#L299)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
>     update_and_calculate_crime_csv(geo_codes, '2019_cleaned.csv',
>                                    '2019_calculated.csv')
> ```

Wondering why aren't we calling this in the loop for every year?
</blockquote></details>

Leave a todo there. 
Some year have their uniqueness of the data, so want to test one by one. 
___
*[scripts/fbi/crime/preprocess_test.py, line 32 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTWHFmAjFUzGco49Rb:-MSTrEMK3nRc8D8f_BE6:bdn88pt) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/preprocess_test.py#L32)):*
> take this CSV as input, run update_and_calculate_crime_csv and validate geocodes e2e2?
That's a good point. 
I guess originally  update_and_calculate_crime_csv was under geo_cities  and I have wrote function test instead. 
Add a TODO and would get this when code covers other years.  
___
*[scripts/fbi/crime/README.md, line 3 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTQrB1ECcp8bxLsAdv:-MSTrkdq6eEWiCNL92Ds:bq3xtn6) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/README.md#L3)):*
> take this CSV as input, run update_and_calculate_crime_csv and validate geocodes e2e2?
Each year has different URLs and you wan direct link for all of them, instead of in the code?
___
*[scripts/fbi/crime/README.md, line 16 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTQzNB6miHqt37biLh:-MSTrtjW-noDUp3PTjok:b-w6p3be) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/README.md#L16)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> We blindly add one column with value 1.·
> ```

This value is not used right?
</blockquote></details>

Not really. 
It's only used when there is duplicate city + state, and the one with wrong population is removed. 
I haven't thought about for 2016, if it has duplicates, how to get rid of one yet. 
___
*[scripts/fbi/crime/README.md, line 17 at r5](https://reviewable.io/reviews/datacommonsorg/data/388#-MSTR3-zC5AIz_ey81-j:-MSTsD2y73uNk_2qLXpt:b3u0l50) ([raw file](https://github.com/datacommonsorg/data/blob/ec4cc56d61d58b1608fe1c6cf664a61a67b4f0c1/scripts/fbi/crime/README.md#L17)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> For duplicate city data, we remove the one with wrong population data.
> ```
How do we check "wrong population"?
</blockquote></details>

Google search.

**Comment by pradh** [comment]
I was responding on reviewable.io which didn't let me post the comments post merge:
1. https://screenshot.googleplex.com/6CPLFwjTNCnhwy2
2. https://screenshot.googleplex.com/7jCnrx7hwNFic5y

**Comment by hanlu09205** [comment]
Could because that I have submitted the PR. 
1. SG. Will update in follow up cl. 
2. Both old and new data. It's just I only used 2019 to test that code. Would run it against other years, update code if needed and add test.

**Pull request merged**
