### PR TITLE
Process FBI Crime state level

### PR DESCRIPTION
**Pull request by hanlu09205**
Import FBI crime state level data. 
1) drop legacy rape2 data
2) arson data was not reported at state level

WriteTMCF+CSV 
6RSDt9rz3ZjWPLr

Validate new FBI state, 50 state, 10 StatVar per state, 12 Obs per StatVar
ALjuzVkkHj8AsUi (1)
Validate mix new + prod FBI state, 
Ao23ookUtvDP5bh (1)

prod validation
7xWQJiNohm4MhBd
new data validation
39SfRrq4ZPfyGo3
mix prod + new data validation
9gBZwnKbmjCSst5

All the inconsistency is because of ForcibleRape, which we drop legacy rape due to it's not counted in total ( Already covered in revised version.
C2T7JaqwW4msxGK

For those inconsistent ones, the value is abnormal. Verified that it's because of adding legacy rape. 
xpMTXJ2GzoS5xdi

For the 4 obs_stat_beyond_3sigma ones, 2 of them are because of ForcibleRape. 
Another two, existing values are same as prod. They were on the boundary of beyond 3sigma. 
BmRSouzLvzFiCTG
7xieYFcjw88RDvC

---
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/data/396)

### CODE REVIEW

**Review by pradh — CHANGES_REQUESTED** [review]
Thanks for the validation!

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/396#-:-MTDZfTl6VHRWTyGe9j-:b-e9ns1c)* status: 0 of 9 files reviewed, 13 unresolved discussions (waiting on @hanlu09205)

___
*[scripts/covid_tracking_project/historic_state_data/COVIDTracking_States_StatisticalVariables.mcf, line 1 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDUD0R4GJDemSPVdfq:-MTDUD0R4GJDemSPVdfr:b-eqfw90) ([raw file](https://github.com/datacommonsorg/data/blob/1ccf0500dceb64b03f0368e7695b9d625b9e5948/scripts/covid_tracking_project/historic_state_data/COVIDTracking_States_StatisticalVariables.mcf#L1)):*
> ```
> Node: dcid:CumulativeCount_MedicalTest_COVID_19
> ```

Why delete this file in this PR?
___
*[scripts/fbi/crime/common_util.py, line 16 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDUhA2DNmfkR-orH4C:-MTDUhA2DNmfkR-orH4D:b1empqz) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/common_util.py#L16)):*
> ```
> path.insert(1, '../../../')
> ```

Comment what this is for?
___
*[scripts/fbi/crime/geocode_cities.py, line 68 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDY2bU8DHy31YC0ycM:-MTDY2bU8DHy31YC0ycN:bhoqqx6) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/geocode_cities.py#L68)):*
> ```
> def find_crime_state(crime):
> ```

Add a brief comment on arg?
___
*[scripts/fbi/crime/preprocess_states.py, line 124 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDYwUnDrOZg2GNnSfq:-MTDYwUnDrOZg2GNnSfr:b-dp655u) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L124)):*
> ```
>         print('{} {} violent mismatch {} {}'.format(r['Year'], r['State'],
>                                                     violent, violent_computed))
> ```

When does this deviate?
___
*[scripts/fbi/crime/preprocess_states.py, line 144 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDZ-EoC9qTZjkwayDx:-MTDZ-EoC9qTZjkwayDy:bnt63uc) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L144)):*
> ```
>         print('{} {} property mismatch {} {}'.format(r['Year'], r['State'],
>                                                      property,
>                                                      property_computed))
> ```
When does this deviate?
___
*[scripts/fbi/crime/preprocess_states.py, line 146 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDYnuK88PNksoRsRB-:-MTDYnuK88PNksoRsRB0:b5vp6u4) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L146)):*
> ```
>   #+ arson
> ```
Remove.

To confirm, state data does not include arson ?
___
*[scripts/fbi/crime/preprocess_states.py, line 156 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDWtFy9PdosfsSukwr:-MTDWtFy9PdosfsSukws:b4hy6xq) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L156)):*
> ```
> , one for every city.
> ```
state?
___
*[scripts/fbi/crime/preprocess_states.py, line 161 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDWwedCSD7CQGGDdrk:-MTDWwedCSD7CQGGDdrl:bazy53t) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L161)):*
> ```
> city
> ```
state
___
*[scripts/fbi/crime/preprocess_states.py, line 194 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDXMfo2MRb6s519N8c:-MTDXMfo2MRb6s519N8d:b-yi5tvq) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L194)):*
> ```Python
>         if field[_STATE_INDEX] and field[_STATE_INDEX] != '""':
>             # Remove numeric values from state names (comes from footnotes)
>             state = cu.remove_digits(field[_STATE_INDEX])
> ```

else:
   // assert state is not empty?
___
*[scripts/fbi/crime/preprocess_states.py, line 280 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDZQOw25vyqrlQSav8:-MTDZQOw25vyqrlQSav9:b9q2uto) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L280)):*
> ```
> cleaned_csv_file = 'cleaned_file.csv'
> ```

No change is required, but for my understanding... why do you choose to create/cleanup all these temporary files?  Any reason they cannot be pandas tables instead?
___
*[scripts/fbi/crime/preprocess_states.py, line 302 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDVmcu0oRAPHGg_fQ-:-MTDVmcu0oRAPHGg_fQ0:bhpmd2g) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L302)):*
> ```
>         with open(xls_file, 'wb') as file:
>             file.write(response.content)
> ```

[For future PR] how big are these files? can we save them in github or https://git-lfs.github.com in case the source URL goes away ?
___
*[scripts/fbi/crime/preprocess_states.py, line 304 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDW65V1Ijpk4mljxJg:-MTDW65V1Ijpk4mljxJh:bw4hkv3) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L304)):*
> ```
> skiprows=[0, 1, 2]
> ```
Add a comment?
___
*[scripts/fbi/crime/preprocess_states.py, line 306 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDWNyu2dPfog-_YB0t:-MTDWNyu2dPfog-_YB0u:bgutsnc) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L306)):*
> ```
> included the
> ```
nit: ... included in the total count, nor in ...

**Review by hanlu09205 — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/396#-:-MTEkZwk8at7C7pABLa0:b-9qdoz3)* status: 0 of 9 files reviewed, 12 unresolved discussions (waiting on @hanlu09205 and @pradh)

___
*[scripts/fbi/crime/preprocess_states.py, line 124 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDYwUnDrOZg2GNnSfq:-MTEbuIN-E_9zzN_JxiZ:bsop38n) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L124)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
>         print('{} {} violent mismatch {} {}'.format(r['Year'], r['State'],
>                                                     violent, violent_computed))
> ```

When does this deviate?
</blockquote></details>

For state, this never happen. City data does happen.
___
*[scripts/fbi/crime/preprocess_states.py, line 144 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDZ-EoC9qTZjkwayDx:-MTEbzt7-umXdn12i3Uu:b55v2qx) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L144)):*
> For state, this never happen. City data does happen.
Ditto
___
*[scripts/fbi/crime/preprocess_states.py, line 146 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDYnuK88PNksoRsRB-:-MTEc8wf1XNhSjU9rzdP:b-djgd96) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L146)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
>   #+ arson
> ```
Remove.

To confirm, state data does not include arson ?
</blockquote></details>

Yes. I mentioned this in README. 
Arson data is not reported at state level. Per FBI: "Although arson data are included in the trend and clearance tables, sufficient data are not available to estimate totals for this offense. Therefore, no arson data are published in this table."
___
*[scripts/fbi/crime/preprocess_states.py, line 156 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDWtFy9PdosfsSukwr:-MTEceIJDC2QzA6oyq0c:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L156)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> , one for every city.
> ```
state?
</blockquote></details>

Done.
___
*[scripts/fbi/crime/preprocess_states.py, line 161 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDWwedCSD7CQGGDdrk:-MTEcljt61fg10vHlJzB:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L161)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> city
> ```
state
</blockquote></details>

Done.
___
*[scripts/fbi/crime/preprocess_states.py, line 194 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDXMfo2MRb6s519N8c:-MTEcsEJ8w1WVapg2K4M:byg1d4e) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L194)):*
> ```
> state = cu.remove_digits(field[_STATE_INDEX])
> ```
There is legitimate case where some row doesn't have state column set. 
As far as there are in total 50 states, that's fine. 
I checked for each year, there are always 50 states. 
___
*[scripts/fbi/crime/preprocess_states.py, line 280 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDZQOw25vyqrlQSav8:-MTEd7t1DzeuVvXvDFbI:br7o4sk) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L280)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> cleaned_csv_file = 'cleaned_file.csv'
> ```

No change is required, but for my understanding... why do you choose to create/cleanup all these temporary files?  Any reason they cannot be pandas tables instead?
</blockquote></details>

Good question. This was branched from existing code and it didn't use pandas table. Instead it has couple stages of file. 
And when I updated upon it, I followed it flow, and didn't make a big refactor as I am also not that comfortable with pandas. 
___
*[scripts/fbi/crime/preprocess_states.py, line 302 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDVmcu0oRAPHGg_fQ-:-MTEdpsP5UcP6YXW9dt7:b-yaqnpd) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L302)):*
> https://git-lfs.github.com
hanluc-macbookpro:crime hanluc$ ls -ltr *.xls
-rw-r--r--  1 hanluc  primarygroup  111104 Feb 10 21:53 2019.xls
-rw-r--r--  1 hanluc  primarygroup  122880 Feb 10 21:53 2018.xls
-rw-r--r--  1 hanluc  primarygroup   93696 Feb 10 21:53 2017.xls
-rw-r--r--  1 hanluc  primarygroup  101888 Feb 10 21:53 2016.xls
-rw-r--r--  1 hanluc  primarygroup   98304 Feb 10 21:53 2015.xls
-rw-r--r--  1 hanluc  primarygroup   99328 Feb 10 21:53 2014.xls
-rw-r--r--  1 hanluc  primarygroup   95744 Feb 10 21:53 2013.xls
-rw-r--r--  1 hanluc  primarygroup   92672 Feb 10 21:53 2012.xls
-rw-r--r--  1 hanluc  primarygroup   99840 Feb 10 21:53 2011.xls
-rw-r--r--  1 hanluc  primarygroup   90112 Feb 10 21:53 2010.xls
-rw-r--r--  1 hanluc  primarygroup   79360 Feb 10 21:53 2009.xls
-rw-r--r--  1 hanluc  primarygroup   75264 Feb 10 21:53 2008.xls

Do you want to save them under this directory or maybe a subdirectory say source?

I could add them, but think code could still script from URL?
___
*[scripts/fbi/crime/preprocess_states.py, line 304 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDW65V1Ijpk4mljxJg:-MTEjAZk8FJfq-G4uqKc:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L304)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> skiprows=[0, 1, 2]
> ```
Add a comment?
</blockquote></details>

Done.

**Review by hanlu09205 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/396)* status: 0 of 9 files reviewed, 12 unresolved discussions (waiting on @hanlu09205 and @pradh)

___
*[scripts/fbi/crime/geocode_cities.py, line 68 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDY2bU8DHy31YC0ycM:-MTEleMb0entZlBl_BbA:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/geocode_cities.py#L68)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> def find_crime_state(crime):
> ```

Add a brief comment on arg?
</blockquote></details>

Done.
___
*[scripts/fbi/crime/preprocess_states.py, line 144 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDZ-EoC9qTZjkwayDx:-MTEkixn4eItXb8eEd27:b-y4ux8d) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L144)):*
<details><summary><i>Previously, hanlu09205 wrote…</i></summary><blockquote>

> For state, this never happen. City data does happen.
Ditto
</blockquote></details>

For state, this never happen. City data does happen.

**Review by hanlu09205 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/396)* status: 0 of 9 files reviewed, 12 unresolved discussions (waiting on @pradh)

___
*[scripts/covid_tracking_project/historic_state_data/COVIDTracking_States_StatisticalVariables.mcf, line 1 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDUD0R4GJDemSPVdfq:-MTEmu5D1JwZTBODM4nU:bjdtray) ([raw file](https://github.com/datacommonsorg/data/blob/1ccf0500dceb64b03f0368e7695b9d625b9e5948/scripts/covid_tracking_project/historic_state_data/COVIDTracking_States_StatisticalVariables.mcf#L1)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

Why delete this file in this PR?
</blockquote></details>

I don't know what happened...
___
*[scripts/fbi/crime/common_util.py, line 16 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDUhA2DNmfkR-orH4C:-MTEmx9qAL7BUkg4TvOi:b-896fix) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/common_util.py#L16)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> path.insert(1, '../../../')
> ```

Comment what this is for?
</blockquote></details>

Done.

**Review by pradh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/396)* status: 0 of 9 files reviewed, 12 unresolved discussions (waiting on @hanlu09205 and @pradh)

___
*[scripts/fbi/crime/common_util.py, line 16 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDUhA2DNmfkR-orH4C:-MTiaHDgD74hZkb7-5Nw:b-3nyo2b) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/common_util.py#L16)):*
<details><summary><i>Previously, hanlu09205 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like you commented a similar insert in another file, not this one.
___
*[scripts/fbi/crime/preprocess_states.py, line 194 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDXMfo2MRb6s519N8c:-MTiayL0-opzQ4UsWEfA:b-p8espx) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L194)):*
<details><summary><i>Previously, hanlu09205 wrote…</i></summary><blockquote>

> ```
> state = cu.remove_digits(field[_STATE_INDEX])
> ```
There is legitimate case where some row doesn't have state column set. 
As far as there are in total 50 states, that's fine. 
I checked for each year, there are always 50 states. 
</blockquote></details>

If state is empty, should we continue?
___
*[scripts/fbi/crime/preprocess_states.py, line 302 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDVmcu0oRAPHGg_fQ-:-MTibDBS85SxBwpdSM0s:b-tb93j2) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L302)):*
<details><summary><i>Previously, hanlu09205 wrote…</i></summary><blockquote>

> https://git-lfs.github.com
hanluc-macbookpro:crime hanluc$ ls -ltr *.xls
-rw-r--r--  1 hanluc  primarygroup  111104 Feb 10 21:53 2019.xls
-rw-r--r--  1 hanluc  primarygroup  122880 Feb 10 21:53 2018.xls
-rw-r--r--  1 hanluc  primarygroup   93696 Feb 10 21:53 2017.xls
-rw-r--r--  1 hanluc  primarygroup  101888 Feb 10 21:53 2016.xls
-rw-r--r--  1 hanluc  primarygroup   98304 Feb 10 21:53 2015.xls
-rw-r--r--  1 hanluc  primarygroup   99328 Feb 10 21:53 2014.xls
-rw-r--r--  1 hanluc  primarygroup   95744 Feb 10 21:53 2013.xls
-rw-r--r--  1 hanluc  primarygroup   92672 Feb 10 21:53 2012.xls
-rw-r--r--  1 hanluc  primarygroup   99840 Feb 10 21:53 2011.xls
-rw-r--r--  1 hanluc  primarygroup   90112 Feb 10 21:53 2010.xls
-rw-r--r--  1 hanluc  primarygroup   79360 Feb 10 21:53 2009.xls
-rw-r--r--  1 hanluc  primarygroup   75264 Feb 10 21:53 2008.xls

Do you want to save them under this directory or maybe a subdirectory say source?

I could add them, but think code could still script from URL?
</blockquote></details>

Maybe we could add them to the sub-directory?

**Review by hanlu09205 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/data/396)* status: 0 of 9 files reviewed, 12 unresolved discussions (waiting on @pradh)

___
*[scripts/fbi/crime/common_util.py, line 16 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDUhA2DNmfkR-orH4C:-MTkxfWI3Oq0u3hLTlG4:bs7wumx) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/common_util.py#L16)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

Looks like you commented a similar insert in another file, not this one.
</blockquote></details>

Done. 
___
*[scripts/fbi/crime/preprocess_states.py, line 194 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDXMfo2MRb6s519N8c:-MTkyVvs9bNCCUMNzHLM:ble7d85) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L194)):*
> state = cu.remove_digits(field[_STATE_INDEX])
Yes. 
Since most of the lines have state empty. 
Here is example, 
2008,ARIZONA,Metropolitan Statistical Area,,6032461,,,,,,,,,,
2008,,,Area actually reporting,0.995,27035,398,1583,9549,15505,266499,53086,177436.0,35977.0,
2008,,,Estimated total,1,27133,399,1590,9579,15565,267708,53361,178233.0,36114.0,
2008,,Cities outside metropolitan areas, ,202505,, ,,,,,,,,
2008,,,Area actually reporting,0.837,801,3,41,80,677,6546,1511,4471.0,564.0,
2008,,,Estimated total,1,958,4,49,96,809,7820,1805,5341.0,674.0,
2008,,Nonmetropolitan counties,,265214,,,,,,,,,,
2008,,,Area actually reporting,1,968,4,34,22,908,3392,1315,1647.0,430.0,
2008,,State Total,,6500180,29059,407,1673,9697,17282,278920,56481,185221.0,37218.0,
2008,,,"Rate per 100,000 inhabitants",,447,6.3,25.7,149.2,265.9,4291,868.9,2849.5,572.6,

But I see your point. Add an assert check for total state number. 
___
*[scripts/fbi/crime/preprocess_states.py, line 302 at r1](https://reviewable.io/reviews/datacommonsorg/data/396#-MTDVmcu0oRAPHGg_fQ-:-MTkximM1KsGh7fqJQl4:b-p4r1pt) ([raw file](https://github.com/datacommonsorg/data/blob/225dab8a38a2fdeb951974d6c16bede65a058883/scripts/fbi/crime/preprocess_states.py#L302)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

Maybe we could add them to the sub-directory?
</blockquote></details>

SG. I am thinking sub-directory source_data, then under souce_data, another two directories states vs cities. 
And maybe follow up RP?

**Pull request merged**
